### ISSUE TITLE
HC5861 - 1.0.7.13499s  安装新版SS插件依旧无法显示

### ISSUE THREAD

**Issue by Canon88** [qiwihui/hiwifi-ss#1]
版本:HC5861 - 1.0.7.13499s  
执行最新的脚本之后报了如下信息:
`root@Hiwifi:/tmp/1# sh shadow.sh 

/*教程请参考:极路由Shadowsocks家庭无痛翻墙实践*/
https://luolei.org/hiwifi-shadowsocks/
by @foru17

那一天,
人类终于回想起了,
曾经一度被他们所支配的恐怖,
还有被囚禁于鸟笼中的那份屈辱.

進撃の巨人 諫山創

Building environment... 创建临时目录ing

Done! 成功创建临时目录!

Downloading files... 下载插件ing

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  188k  100  188k    0     0  1988k      0 --:--:-- --:--:-- --:--:-- 2273k
Done! 下载完成

Installing... 安装ing
Done! 插件安装成功!

adding uninstall information... 准备删除临时文件...

cleanning temporary files... 清理临时文件ing

luci-cache does not exist! 无法找到luci-cache,请确定是否是极路由环境

the whole installation Success! 插件成功安装!
1987年9月14日21时07分
中国第一封电子邮件
从北京发往德国
越过长城，走向世界
Done! Hello World! 一切就绪,你好世界!`

重启路由器在网络设置下面没有SS设置.不知道是为什么.
![image](https://cloud.githubusercontent.com/assets/19372121/17374567/d0169300-59df-11e6-84b8-8a7320462177.png)

**Comment by qiwihui** [comment]
@Canon88 你的hiwifi没有成功是我忘记修改`shadow.sh`里的脚本地址了，现在已经修改了

**Comment by Canon88** [comment]
好的 是否直接下载重新安装即可.不需要单独卸载吧?



115664000@qq.com
 
发件人： qiwihui
发送时间： 2016-08-04 12:07
收件人： qiwihui/hiwifi-ss
抄送： Canon88; Mention
主题： Re: [qiwihui/hiwifi-ss] HC5861 - 1.0.7.13499s 安装新版SS插件依旧无法显示 (#1)
@Canon88 你的hiwifi没有成功是我忘记修改shadow.sh里的脚本地址了，现在已经修改了

**Comment by qiwihui** [comment]
不需要卸载，直接下载安装就可以了。

**Comment by Canon88** [comment]
好的 非常感谢.等下班回去试试~



115664000@qq.com
 
发件人： qiwihui
发送时间： 2016-08-04 14:38
收件人： qiwihui/hiwifi-ss
抄送： Canon88; Mention
主题： Re: [qiwihui/hiwifi-ss] HC5861 - 1.0.7.13499s 安装新版SS插件依旧无法显示 (#1)
不需要卸载，直接下载安装就可以了。

**Comment by Canon88** [comment]
@qiwihui 你好.我刚试了一下依旧是同样的错
`root@Hiwifi:~# sh shadow.sh 

/*教程请参考:极路由Shadowsocks家庭无痛翻墙实践*/
https://luolei.org/hiwifi-shadowsocks/
by @foru17


那一天,
人类终于回想起了,
曾经一度被他们所支配的恐怖,
还有被囚禁于鸟笼中的那份屈辱.

進撃の巨人 諫山創

Building environment... 创建临时目录ing

Done! 成功创建临时目录!


Downloading files... 下载插件ing


  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   125    0   125    0     0     25      0 --:--:--  0:00:04 --:--:--    25
Done! 下载完成


Installing... 安装ing
tar: invalid gzip magic
Done! 插件安装成功!


adding uninstall information... 准备删除临时文件...


cleanning temporary files... 清理临时文件ing


luci-cache does not exist! 无法找到luci-cache,请确定是否是极路由环境


the whole installation Success! 插件成功安装!
1987年9月14日21时07分
中国第一封电子邮件
从北京发往德国
越过长城，走向世界
Done! Hello World! 一切就绪,你好世界!`
退出了极路由再进去还是没有SS.
![image](https://cloud.githubusercontent.com/assets/19372121/17400018/31ca193a-5a78-11e6-8de8-8d54f03577b7.png)

**Comment by qiwihui** [comment]
@Canon88 我修改了下载链接到我的服务器上，已测试可用。使用下边的命令就可以了。

```sh
cd /tmp && curl -k -o shadow.sh https://raw.githubusercontent.com/qiwihui/hiwifi-ss/master/shadow.sh && sh shadow.sh && rm shadow.sh
```

里面的一些显示问题可以暂时忽略，我会在这些天完善。

**Comment by Lstoryc** [comment]
我也出现一样的问题 安装完后看不到 ss那个按钮。，。

**Comment by qiwihui** [comment]
@Canon88 @Lstoryc 真是很抱歉，我上传错文件了 :( 。 现在已经更改成新文件了。

**Comment by Lstoryc** [comment]
可以了 主要功能能玩，样式待优化 

thx

**Comment by qiwihui** [comment]
多谢支持 @Canon88 @Lstoryc .

**Comment by Canon88** [comment]
非常感谢已经可以正常使用.



115664000@qq.com
 
发件人： qiwihui
发送时间： 2016-08-04 23:43
收件人： qiwihui/hiwifi-ss
抄送： Canon88; Mention
主题： Re: [qiwihui/hiwifi-ss] HC5861 - 1.0.7.13499s 安装新版SS插件依旧无法显示 (#1)
@Canon88 我修改了下载链接到我的服务器上，已测试可用。使用下边的命令就可以了。
cd /tmp && curl -k -o shadow.sh https://raw.githubusercontent.com/qiwihui/hiwifi-ss/master/shadow.sh && sh shadow.sh && rm shadow.sh
里面的一些显示问题可以暂时忽略，我会在这些天完善。

**Comment by kenchoh** [comment]
我的显示请求的接口不存在

**Comment by qiwihui** [comment]
@kenchoh 请重启路由器试试

**Comment by kenchoh** [comment]
@qiwihui 可以了 感谢

**Comment by i7worlds** [comment]
请教……～ 遇到 错误提示如下：luci-cache does not exist! 无法找到luci-cache,请确定是否是极路由环境。在后台页面有SS导航菜单，但是点击跳出“文件未找到... ”。所用的型号为极路由3 系统版本：HC5861 - 1.0.7.13499s 。候教……谢谢！

**Comment by qiwihui** [comment]
@i7worlds  #16

**Comment by qiwihui** [comment]
referring to #38

**Comment by LukeLK** [comment]
求教，填写好了内容没有任何反应，一直显示“未运行”……

**Comment by winglight** [comment]
脚本之前是没问题的，出去玩了一个星期回来发现极路由自动更新固件了。。。现在版本是：
HC5962 - 1.2.5.15805s
运行脚本没有出错，但是插件的按钮没显示出来，不知道是什么问题？

**Comment by ludengji** [comment]
系统版本 : HC5661A - 1.2.5.15805s 极路由刷了之后，互联网那里一直转圈圈无内容，F12查看没有脚本错误。是啥原因呢。。
![image](https://cloud.githubusercontent.com/assets/4989601/20976327/2a5fb67e-bcdd-11e6-8cfd-c9fa65cb8d20.png)

**Comment by winglight** [comment]
我的版本是：
HC5962 - 1.2.5.15805s
已经成功翻墙，感谢LZ！

**Comment by Steve-Mr** [comment]
我的版本是 HC5962-1.2.5.15805s 安装之后会在互联网那里不停转圈显示不出来

**Comment by nicajonh** [comment]
HC5861 - 1.2.5.15805s 也是互联网那里不停转圈显示不出来

**Comment by blackielee** [comment]
我也转菊花 求大神帮忙解决 谢谢

**Comment by JohnnyChenS** [comment]
我的版本也是HC5661 - 1.2.5.15805s 也在转菊花！！救命！

**Comment by Minami-Kotori** [comment]
1.2.5.15805s 同有这个问题 真是不该升固件

**Comment by winglight** [comment]
有转圈问题的都试一下新脚本：cd /tmp && curl -k -o shadow.sh https://raw.githubusercontent.com/qiwihui/hiwifi-ss/master/shadow.sh && sh shadow.sh && rm shadow.sh

**Comment by Minami-Kotori** [comment]
已成功运行 谢谢大佬 thx

**Comment by JohnnyChenS** [comment]
@winglight 
hello 老大， 我就是用的最新的脚本，并且我刚才又试了一遍你回复里的命令，依然还是在转菊花啊。。T.T 求助！已经好几个星期翻不出来了。。

**Comment by JohnnyChenS** [comment]
@Minami-Kotori 你可以了吗？为什么我重新刷了好几遍都还是不行...我的版本和你一样

**Comment by winglight** [comment]
脚本不是我写的，我只是尝试了一下，刚好运气好就成功了吧，下次好了，记得不要设置自动更新极路由版本

**Comment by JohnnyChenS** [comment]
@winglight 我今晚回家再试试... T。T
