### ISSUE TITLE
混淆模式无法加速

### ISSUE THREAD

**Issue by konts** [qiwihui/hiwifi-ss#100]
#### 问题描述
配置信息
服务器地址：
服务器端口：
加密方式：chacha20
密码：
协议：auth_aes128_md5
协议参数：
混淆：tls1.2_ticket_auth
混淆参数：cn.bing.com
#### 运行结果
未加速，怎么破

**Comment by Myoko** [comment]
目前不支持混淆模式吧。

**Comment by qiwihui** [comment]
@konts 不支持SSR

@konts @Myoko 最新版本v1.0.6支持simple-obfs混淆。
