### ISSUE TITLE
极路由4，HC5962 - 1.3.4.18145s，刷了最新的固件无法使用

### ISSUE THREAD

**Issue by 823michael** [qiwihui/hiwifi-ss#101]
#### 问题描述
成功配置并打开SS之后，整个路由器都无法上网了。要关闭，或者SS没有正常运行才可以正常上网，但是就无法使用SS了。。
#### 运行结果
SS不起作用，望修复，感谢！

**Comment by beyondkmp** [comment]
可以用，完全没问题

**Comment by 823michael** [comment]
@beyondkmp 谢谢分享，我又重新恢复出厂设置了一次，另外选中了 格式化 加密分区(插件)这个选项，再重新装支持1.3.4.18145s的插件：

cd /tmp && curl -k -o shadow.sh https://raw.githubusercontent.com/qiwihui/hiwifi-ss/master/shadow.sh && sh shadow.sh && rm shadow.sh

就OK了。

之前可能是先装了不支持1.3.4.18145s版本的插件，然后恢复出厂设置的时候又没有选这个格式化插件的选项。随后我虽然又重新装了支持1.3.4.18145s插件，但是就出现了描述的问题。
