### ISSUE TITLE
问题反馈1.3.4.18145s固件！刷入SS后关闭SS后依然是开启状态

### ISSUE THREAD

**Issue by Myoko** [qiwihui/hiwifi-ss#103]
#### 问题描述
1.3.4.18145s固件！刷入SS后关闭SS无用！点击上面的开关了 依然是显示开启状态！只是SS并没有连接而已
<img width="763" alt="default" src="https://cloud.githubusercontent.com/assets/3013386/26830880/f4933602-4afc-11e7-8c9a-f21ce2584b81.png">

**Comment by HTCXMAS** [comment]
我也是遇到相同的情况，但是不是很影响使用。关了过后就不会走SS了！不过这个BUG希望能修复。

**Comment by MrWanyan** [comment]
新版本的SS插件安装地址可以共享一下嘛~

**Comment by aQuaYi** [comment]
@MrWanyan 在命令行用脚本安装就可以了。
cd /tmp && curl -k -o shadow.sh https://raw.githubusercontent.com/qiwihui/hiwifi-ss/master/shadow.sh && sh shadow.sh 12515805s && rm shadow.sh

**Comment by qiwihui** [comment]
已修复，重新安装即可。
