### ISSUE TITLE
用了ss，仍然无法访问的网站收集（比如google.co.uk）

### ISSUE THREAD

**Issue by sinkcup** [qiwihui/hiwifi-ss#104]
google.co.uk 无法访问

**Comment by benjaminv** [comment]
same issue here. tested a lot of DNS.

**Comment by sinkcup** [comment]
d2vfwqvbhx0bib.cloudfront.net 无法访问，比如：

https://d2vfwqvbhx0bib.cloudfront.net/phpcodechecker/assets/css/combined.ssl.min.css

**Comment by sinkcup** [comment]
em.facebookmail.com 无法访问。chrome报错：找不到 em.facebookmail.com 的服务器 DNS 地址。

**Comment by qiwihui** [comment]
google.co.uk 无法访问是因为当前 release 的版本（v1.0.5）中的 dnsmasq 规则没有完全包括 gfwlist 中被墙的网站。

解决办法：

参照README中 [本地更新dnsmasqconf](https://github.com/qiwihui/hiwifi-ss#本地更新dnsmasqconf) 方法更新最新的规则列表；

这个问题在最新的版本中已经解决，会尽快发布。

**Comment by q629988171** [comment]
@qiwihui 现在hiwifi-ss 不是用白名单模式了吗？非国内IP全部走代理，这个最好，不用考虑更新名单（国内IP已经饱和不太可能再分配）

**Comment by qiwihui** [comment]
支持gfwlist更新，也支持白名单模式了
