### ISSUE TITLE
没有“导入配置文件”和“高级设置”这两个选项

### ISSUE THREAD

**Issue by miniwhite2000** [qiwihui/hiwifi-ss#108]
#### 问题描述
运行完脚本，SS正常使用，但是没有“导入配置文件”和“高级设置”这两个选项。
两个脚本都运行了，都是一样的没有这两个选项。极路由3软件最新版。

**Comment by lane333999** [comment]
我也是！试过重启也不行
![default](https://user-images.githubusercontent.com/17093487/27506985-400af81e-58f8-11e7-8e1a-a0a75edb113a.jpg)

**Comment by benjaminv** [comment]
me too, at 系统版本 : HC5761 - 1.2.5.15805s

**Comment by leogeng** [comment]
me too

**Comment by novamx** [comment]
4台极路由设备 都没有这个选项了

**Comment by qiwihui** [comment]
这个功能暂时关闭了，请查看新的 README
