### ISSUE TITLE
HC5761 - 1.3.4.18145s  安装后点击互联网标签一直转菊花呢

### ISSUE THREAD

**Issue by victorsun1986** [qiwihui/hiwifi-ss#109]
#### 问题描述
HC5761 - 1.3.4.18145s 
#### 运行结果
 安装后点击互联网标签一直转菊花呢

使用的是
cd /tmp && curl -k -o shadow.sh https://raw.githubusercontent.com/qiwihui/hiwifi-ss/master/shadow.sh && sh shadow.sh && rm shadow.sh

**Comment by qiwihui** [comment]
已将标签移到左侧菜单，重新安装可以看到
