### ISSUE TITLE
支持 chacha20 加密方式

### ISSUE THREAD

**Issue by qiwihui** [qiwihui/hiwifi-ss#11]
如题

**Comment by hkbobi** [comment]
我安装的还看不到chacha20加密方式，什么时候可以呢

**Comment by qiwihui** [comment]
@hkbobi 这个是给自己提的issue，一旦增加了chacha20，就会在这边更新。

**Comment by xiaolei16fan** [comment]
支持chacha20加密非常好，期待！

**Comment by qiwihui** [comment]
@hkbobi @xiaolei16fan 最新工作比较忙，这个功能其实已经想好怎么弄了，就是还差去实施，我会抽时间来支持这个功能。感谢支持！

**Comment by qiwihui** [comment]
@hkbobi @xiaolei16fan 支持`chacha20`咯😄

**Comment by qiwihui** [comment]
also 1330a0581c6ccd77febf02269de846bd328ac7ad as upgrade ss version
