### ISSUE TITLE
不知为何经常性的提示 “运行中 未加速” 已经看过所有issue

### ISSUE THREAD

**Issue by Mosney** [qiwihui/hiwifi-ss#113]
#### 问题描述
经常性的  “运行中 未加速”    
重启无效 点击保存等待后无效 重启路由器无效
网络环境为校园固定IP/DNS ss服务器是一定没有问题的 本机已经测试过
#### 运行结果
 “运行中 未加速”

**Comment by Mosney** [comment]
HC5962 - 1.3.5.18462s 
目前路由器是极4HC5962  固件版本如上  刚刚注意到最新的ss.tar.gz似乎是一个月钱“支持 1.3.4.18145s”的版本 ，还请作者查看是否因为固件版本太高导致的蜜汁问题 @qiwihui

**Comment by qiwihui** [comment]
已修复这个问题，描述更清楚了，重新安装即可。
