### ISSUE TITLE
新版本后台界面shadows插件消失 HC5962 - 1.3.5.18462s

### ISSUE THREAD

**Issue by CoreyXPX** [qiwihui/hiwifi-ss#114]
#### 问题描述
极路由系统自动升级后，shadowsocks插件在操作界面消失

#### 运行结果

重新运行脚本后仍然如此。

**Comment by isping** [comment]
刚才遇到同样问题，求解？

**Comment by Lstoryc** [comment]
同上 我的版本是  HC5962 - 1.3.5.18462s

**Comment by isping** [comment]
解决办法：
1.备份相关账号密码，恢复极路由出厂设置；（注：恢复后好像仍然是固件版本： HC5962 - 1.3.5.18462s，不过没关系；-）
2.使用新版脚本安装，安装成功可见左下方小飞机(安全上网)，设置和原来相同。无痛冲浪中……

`cd /tmp && curl -k -o shadow.sh https://raw.githubusercontent.com/qiwihui/hiwifi-ss/master/shadow.sh && sh shadow.sh && rm shadow.sh`

**Comment by livehl** [comment]
艹，我的也是自动升级了。流氓

**Comment by BenjaminX** [comment]
升级 ROM 都会丢失，需要重新安装。

**Comment by YinChangSheng** [comment]
无语了，被强制升级了，感觉越升级越慢，强制换机器的节奏

**Comment by qiwihui** [comment]
已升级 hiwifi-ss，支持之前配置保存和新界面，可以更新了
