### ISSUE TITLE
是否能够加入 SS-Libev 从 v3.0 起加入的 AEAD

### ISSUE THREAD

**Issue by kotomei** [qiwihui/hiwifi-ss#117]

**Comment by qiwihui** [comment]
暂时未找到 ss-libev 的极路由编译的版本, 正在尝试手动编译

**Comment by qnmlgdsb** [comment]
等待大佬的好消息

**Comment by BenjaminX** [comment]
期待还有 SSR 的加入

**Comment by love6743** [comment]
什么时候能支持SSR

**Comment by Kevi0128** [comment]
期待大佬的好消息，就我实际使用来说，如果使用非AEAD加密，我的SS服务器会被检测到，导致SS服务出现问题，使用了AEAD的aes-256-gcm加密后这个问题就没出现了，所以很是期待大佬能够把AEAD加密加上去

**Comment by suifeng584** [comment]
大佬，我这边已经交叉编译了libev（v3.0.8）的静态版本，我可以提交给你。
ss-local  ss-manager  ss-nat  ss-redir  ss-server  ss-tunnel

 file ss-redir
ss-redir: ELF 32-bit LSB  executable, MIPS, MIPS32 rel2 version 1 (SYSV), statically linked, stripped

**Comment by qiwihui** [comment]
@suifeng584 谢谢你编译的版本，非常感谢支持！会在最近测试一下并加入到项目中。再次感谢！

**Comment by suifeng584** [comment]
大佬，我这边simple-obfs，ssr-libev版本（2.5.6）也都静态编译OK，有需要的话，也可以提供。

**Comment by qiwihui** [comment]
@suifeng584 好的，谢谢，我先测试完这边的 ss。

**Comment by qiwihui** [comment]
已经更新了对 ss 3.0.8的支持。参见 commit 3876d4ab67fe1ef302f61d212ac95a0f51e8eca3

**Comment by qiwihui** [comment]
编译方式请参考 https://haoutil.com/topic/cross-compile-shadowsocks-libev

**Comment by dreamyphone** [comment]
@suifeng584 大佬，你变易好的这几个文件能给我发一份吗？非常感激。
dreamyphone@foxmail.com

    1. ss-manager
    2. ss-nat 
    3. ss-redir 
    4. ss-server 
    5. ss-tunnel 
    6. ss-redir
    7. ss-local 
    8. simple-obfs 
    9. ssr-libev
