### ISSUE TITLE
HC5861 - 1.3.4.18145s 无法正常安装

### ISSUE THREAD

**Issue by ChokW** [qiwihui/hiwifi-ss#119]
#### 问题描述
HC5861 - 1.3.4.18145s 无法正常安装
 
安装运行:
cd / tmp && curl -k -o shadow.sh https://raw.githubusercontent.com/qiwihui/hiwifi-ss/master/shadow.sh && sh shadow.sh && rm shadow.sh

#### 运行结果
rl: (7) Failed to connect to raw.githubusercontent.com port 443: Operation timed out

**Comment by qiwihui** [comment]
网路问题，请重新运行系在命令试试，若不行请发邮件给我。
