### ISSUE TITLE
提供卸载脚步?

### ISSUE THREAD

**Issue by vonhezhou** [qiwihui/hiwifi-ss#12]
#### 问题描述
嗯,安装之后,没有卸载选项,没有卸载脚步.意味着如果想要换一个版本,不知道如何卸载了.

**Comment by vonhezhou** [comment]
研究了一下,把备份的html文件还原,
mv  /usr/lib/lua/luci/view/admin_web/network/index.htm.ssbak  /usr/lib/lua/luci/view/admin_web/network/index.htm
然后
opkg remove geewan-ss
就可以了
标记为close吧

**Comment by yooranchen** [comment]
未找到这个备份的页面,怎么回事

**Comment by xiaoxian77** [comment]
未找到这个备份的页面

**Comment by vonhezhou** [comment]
新版的改了。换这个路径/usr/lib/lua/luci/view/admin_web/menu/menu_left.htm.ssbak，换下面的:
mv /usr/lib/lua/luci/view/admin_web/menu/menu_left.htm.ssbak /usr/lib/lua/luci/view/admin_web/menu/menu_left.htm
其实就是把备份的文件还原了，把文件名的ssbak后缀去掉
新版的系统里，不是有个插件可以方便运行ss吗？我不用了，就没有仔细研究了

**Comment by a86706427** [comment]
运行了这个指令之后好像后台炸掉了，变成了这样
Status: 500 Internal Server Error Failed to execute template dispatcher target for entry '/admin_web'. The called action terminated with an exception: Failed to execute template 'admin_web/home'. A runtime error occured: Failed to load template 'admin_web/menu/menu_left'. Error while parsing template '/usr/lib/lua/luci/view/admin_web/menu/menu_left.htm'. A syntax error occured near 'No such file or directory'. stack traceback: [C]: in function 'assert' ?: in function 'dispatch' ?: in function
怎么解决？

**Comment by vonhezhou** [comment]
我已经没有这个设备了,需要@一下开发者

**Comment by devnakx** [comment]
> 运行了这个指令之后好像后台炸掉了，变成了这样
> Status: 500 Internal Server Error Failed to execute template dispatcher target for entry '/admin_web'. The called action terminated with an exception: Failed to execute template 'admin_web/home'. A runtime error occured: Failed to load template 'admin_web/menu/menu_left'. Error while parsing template '/usr/lib/lua/luci/view/admin_web/menu/menu_left.htm'. A syntax error occured near 'No such file or directory'. stack traceback: [C]: in function 'assert' ?: in function 'dispatch' ?: in function
> 怎么解决？

上面已经说了，用这个命令：
**mv /usr/lib/lua/luci/view/admin_web/menu/menu_left.htm.ssbak /usr/lib/lua/luci/view/admin_web/menu/menu_left.htm**

**Comment by SuperTreeGrove** [comment]
> 运行了这个指令之后好像后台炸掉了，变成了这样
> Status: 500 Internal Server Error Failed to execute template dispatcher target for entry '/admin_web'. The called action terminated with an exception: Failed to execute template 'admin_web/home'. A runtime error occured: Failed to load template 'admin_web/menu/menu_left'. Error while parsing template '/usr/lib/lua/luci/view/admin_web/menu/menu_left.htm'. A syntax error occured near 'No such file or directory'. stack traceback: [C]: in function 'assert' ?: in function 'dispatch' ?: in function
> 怎么解决？

可能需要先  opkg remove geewan-ss
再
mv /usr/lib/lua/luci/view/admin_web/menu/menu_left.htm.ssbak /usr/lib/lua/luci/view/admin_web/menu/menu_left.htm

**Comment by ghost** [comment]
装上去根本就连不上外网，我用着SS-PC就没问题，然后卸载还把主界面搞丢失，什么垃圾，不维护就关了OK？

**Comment by 0b11111111** [comment]
补充以下，所有关于界面的修改可以通过 `find /usr -name "*.ssbak"` 找到，然后进到对应的目录，删掉同名 `.htm` 文件，`mv xx.ssbak xx.htm`。我是比较久之前安装的，找到了两个文件

```plain
/usr/lib/lua/luci/view/admin_mobile/home.htm.ssbak
/usr/lib/lua/luci/view/admin_web/menu/menu_left.htm.ssbak
```

，恢复，最后 `opkg remove geewan-ss` 即可。

**Comment by plxty** [comment]
主界面丢失的是因为 `opkg remove geewan-ss` 把 `menu-left.htm` 删了。。在这个项目下可以找到这个文件，贴上去就好（把最后一个 `<li>` 删掉就行了）。
