### ISSUE TITLE
脚本安装失败，包名错误

### ISSUE THREAD

**Issue by Kevi0128** [qiwihui/hiwifi-ss#121]
在使用脚本安装1.0.5版本的时候，下载的包名为 hiwifi-ss.v1.0.5.tar.gz ，但脚本安装的时候却仍使用了hiwifi-ss.tar.gz包名安装，导致空指针错误，建议下载新包后重命名为hiwifi-ss.tar.gz，因为并不熟悉shell脚本，所以只能提交一个issues了

**Comment by qiwihui** [comment]
修改了包的名称，重新试试
