### ISSUE TITLE
网上找到一个极路由可用的，不知道是否可以参考

### ISSUE THREAD

**Issue by zshwq5** [qiwihui/hiwifi-ss#122]
网上找到一个极路由可用的，不知道是否可以参考
可以选择几种模式

不知道上传附件。这样不知道是否可以？
（删除了两个文件：包中的dnsmasq与ss-redir；包不能直接使用）
链接: https://pan.baidu.com/s/1nveEIzn 密码: w89e

**Comment by qiwihui** [comment]
谢谢你的建议！

P.S

**Comment by zshwq5** [comment]
这样就可以把删除的文件一并上传。
[bin.zip](https://github.com/qiwihui/hiwifi-ss/files/1193231/bin.zip)

如果能够结合起来应该比较完美了。PDNS我这里使用比较好。
