### ISSUE TITLE
允许部分人使用SS

### ISSUE THREAD

**Issue by zimo888** [qiwihui/hiwifi-ss#125]
#### 问题描述
连接路由器的人有很多，能不能增加只允许指定的人使用SS功能的白名单呢。谢谢。

**Comment by qiwihui** [comment]
不支持这种功能。

翻墙，是为了帮助访问被屏蔽的网站和 IP，而不是再次限制人们访问这些网站。
你想要的这个功能gfw已经帮你做了，这种情况下，你不需要一个翻墙软件来实现，你只需要再买一个路由器就可以了。

**Comment by paicha** [comment]
https://github.com/qiwihui/hiwifi-ss/issues/47
可以参考这个添加 iptables 规则
