### ISSUE TITLE
极路由固件升级到1.3.5.18462s后，ss最新版，状态始终“连接错误”

### ISSUE THREAD

**Issue by paperadio** [qiwihui/hiwifi-ss#128]
#### 问题描述
固件：1.3.5.18462s
ss：v1.0.5
最近升级了路由器固件，又装了ss，结果基本上就连不上了。
#### 运行结果
安全上网->服务器配置->状态：连接错误
一打开开关后，就从“检查中”变为“连接错误”，偶尔会变为“连接成功”

**Comment by zshwq5** [comment]
描述不全，搞不清楚这是什么状况。仅知道：状态：连接错误，偶尔会变为“连接成功”
