### ISSUE TITLE
升级路由器固件1.3.5.18462s后，ss基本连不上了

### ISSUE THREAD

**Issue by paperadio** [qiwihui/hiwifi-ss#129]
#### 问题描述
固件：1.3.5.18462s
ss：v1.0.5
最近升级了路由器固件，又装了ss，结果基本上就连不上了。
#### 运行结果
安全上网->服务器配置->状态：连接错误
一打开开关后，就从“检查中”变为“连接错误”，偶尔会变为“连接正常”

**Comment by zshwq5** [comment]
建议描述下路由型号；之前是哪个版本的固件安装的哪个版本；之前是否正常。
另外服务器是否有变动；或是协议是否有变化。
可能与你有相同的路由的好心人会相应回复。。。。。

**Comment by dt99** [comment]
建议直接恢复出厂设置重装

**Comment by paperadio** [comment]
谢谢zshwq5和dt99，我的路由器第二天自动就好了，可能是ss服务提供商的问题吧。当时确实非常不稳定，正好又碰上刚更新完ss插件。谢谢了。
