### ISSUE TITLE
极3 固件1.0.7.13499s 进不了系统web页面

### ISSUE THREAD

**Issue by SamuelXie** [qiwihui/hiwifi-ss#13]
#### 问题描述
按照README中命令使用后，
登录后台出现了web页面全部重定向到 “系统忙，请稍后重试” 页面的问题，无法正常登录，
但依然可以上网，重启尝试过 没有效果，
需要刷固件么？
#### 运行结果
手机端APP管理没有问题，
貌似是PC版和移动版的web页面都挂了。。。
###################
系统忙，请稍后重试... 
点击返回首页
###################

**Comment by SamuelXie** [comment]
已解决，原因是curl -k https://qiwihui.com/ss.tar.gz -o ss.tar.gz有errno，不知为何没速度
自己下载下来https://qiwihui.com/ss.tar.gz传到极路由上，
把之后的粘贴上就好了0.0

**Comment by qiwihui** [comment]
@SamuelXie 可能最近服务器有点不稳定，导致下载的时候没有成功。很高兴你的问题解决了 👍 .

**Comment by qiwihui** [comment]
referring to #38
