### ISSUE TITLE
下载安装插件速度特别慢

### ISSUE THREAD

**Issue by wzs1990** [qiwihui/hiwifi-ss#132]
#### 问题描述
下载安装插件速度特别慢
#### 运行结果
最近下载安装插件速度特别慢

**Comment by qiwihui** [comment]
可能是因为:

1. ss-* 的几个文件在 3.0 以上的版本编译出来之后比较大，下载的包变大了；
2. 使用的是 github 作为文件服务器，访问 github 网络比较慢；

解决：

1. 精简 hiwifi-ss安装包的文件大小；
2. 将文件转存至国内服务器，从国内服务器下载；
