### ISSUE TITLE
HC5861 1.3.4.18145s安装成功状态一直是未运行

### ISSUE THREAD

**Issue by stalxjason** [qiwihui/hiwifi-ss#134]
#### 问题描述
插件安装成功，路由器已重启 关闭所有的加速软件，服务器配置信息正确，开关开启

#### 运行结果
状态提示一直是未运行

**Comment by qiwihui** [comment]
1. 检查安装后的版本是不是最新(v1.0.5);
2. 开关关闭再开启，检查是不是翻墙；
3. 重新安装试试；
4. 试着重置路由器再安装试试；

**Comment by stalxjason** [comment]
版本为v1.0.5，开关重新关闭 打开显示检查中然后显示的未运行。我先试试重新安装

**Comment by stalxjason** [comment]
重置路由器，重新安装可以了

**Comment by qiwihui** [comment]
谢谢~
