### ISSUE TITLE
部分白背景，不能GFWlist黑名单模式--系统版本 : B70 - 1.2.5.15805s

### ISSUE THREAD

**Issue by SouHong** [qiwihui/hiwifi-ss#136]
填写一下以下几个问题

1. 使用的 hiwifi-ss 版本
系统版本 : B70 - 1.2.5.15805s ； B70 - 1.3.5.18462s
2. 问题产生过程
部分白背景，不能GFWlist黑名单模式。
3. 你的期望
解决这两个问题，期待加入SSR支持。
4. 运行结果
解决过程：
*************************************************************************
部分白背景：
*************************************************************************
![1](https://user-images.githubusercontent.com/30280682/29160118-9cac3104-7de3-11e7-9112-22c08ca3c674.png)
修改/usr/lib/lua/luci/view/admin_web/prometheus/index.htm
并在最底下加入如下图
<% include('admin_web/footer') %>

<script type="text/javascript" src="<%=resource%>/v2/js/admin_web/general_module.js?v=<%=ver.svnRevNum%>"></script>
这三行。
图中最后两行可以不需要。
修改/usr/lib/lua/luci/view/admin_web/prometheus/index.htm 其中的ID对应参数
类似"
input type="text" class="input" name="server" tabindex="1" value="" id="ss_server"
"改成"
input type="text" class="input" name="server" tabindex="1" value="" id="server"
"删除其中id=后面的  ss_

![2](https://user-images.githubusercontent.com/30280682/29161955-9925140e-7dea-11e7-8de3-80e3479c9648.png)

![1](https://user-images.githubusercontent.com/30280682/29161810-3202206e-7dea-11e7-8116-ac9c67870e69.png)

*************************************************************************
GFWlist黑名单模式
*************************************************************************
修改方法如下，还可以优化（合并到gw-shadowsocks并优化）。
**仅 B70 - 1.2.5.15805s - 1.3.5.18462s测试正常。断电测试正常。**
1.修改：/etc/init.d/gw-redsocks
"
rs_iptables_add() {
	echo -n > /dev/null
	iptables -t nat -N $appname 
	iptables -t nat -A PREROUTING -i br-lan -j $appname
	iptables -t nat -A OUTPUT -j $appname
	iptables -t nat -A $appname -m salist --salist local --match-dip -j RETURN 
	iptables -t nat -A $appname -m salist --salist hiwifi --match-dip -j RETURN 
	iptables -t nat -A $appname -d $lan_ip/24 -j RETURN
	iptables -t nat -A $appname -d $wanip/24 -j RETURN
	iptables -t nat -A $appname -d $server_ip/32 -j RETURN

	[ "$mode" != "1" ] && {
		ipset create china-banned hash:ip maxelem 65536 2>/dev/null
			ipset add china-banned 91.108.56.0/22
			ipset add china-banned 91.108.4.0/22
			ipset add china-banned 109.239.140.0/24
			ipset add china-banned 149.154.160.0/20
		iptables -t nat -A $appname -m set ! --match-set china-banned dst -j RETURN
		iptables -t nat -A $appname -m set --match-set china dst -j RETURN
		# Get LAN settings as default parameters
	[ -f /lib/functions/network.sh ] && . /lib/functions/network.sh
	[ -z "$covered_subnets" ] && network_get_subnet covered_subnets lan
		local subnet
		for subnet in $covered_subnets; do
		iptables -t nat -A $appname -s $subnet -p tcp -j REDIRECT --to 3088
		done
		iptables -t nat -I PREROUTING -p tcp -j $appname
	#echo this $host is gfwlist
	[ -f /tmp/dnsmasq.d/02-ipset.conf ] || {
		awk '!/^$/&&!/^#/{printf("ipset=/%s/'"china-banned"'\n",$0)}' \
		/etc/gw-shadowsocks/china-banned > /tmp/dnsmasq.d/GFW-ipset.conf
	}
	[ -f /tmp/dnsmasq.d/01-pollution.conf ] || {
		awk '!/^$/&&!/^#/{printf("server=/%s/'"127.0.0.1#53535"'\n",$0)}' \
		/etc/gw-shadowsocks/china-banned > /tmp/dnsmasq.d/01-pollution.conf
	}
	
	iptables -t nat -A $appname -m salist --salist china --match-dip -j RETURN
	iptables -t nat -A $appname -p tcp -m salist --match-dip --salist china-banned -j DNAT --to-destination $lan_ip:$ss_local_port
	}
	
	iptables -t nat -A $appname -p tcp -j DNAT --to-destination $lan_ip:$rs_port_tcp
}
"
2./etc/gw-shadowsocks/添加 china-banned 文件
[china-banned.zip](https://github.com/qiwihui/hiwifi-ss/files/1213978/china-banned.zip) 
china-banned.zip改名为china-banned 放到/etc/gw-shadowsocks/
3.智能模式已经是GFWlist黑名单模式，仅china-banned文件中的域名走SS。
4.删除/etc/gw-shadowsocks/gw-shadowsocks.dnlist

**Comment by qiwihui** [comment]
@SouHong 你将这两个改进提给我两个 PR 吧，谢谢！

**Comment by SouHong** [comment]
@qiwihui 部分白背景处理办法不采用，不能正确读取配置文件内容。已经 PR

**Comment by SouHong** [comment]
@qiwihui 部分白背景问题已经暂时可以正常使用，有两处需要手动输入。我同时把
/usr/lib/lua/luci/controller/api/prometheus.lua修改了两处默认值。
"
result['timeout'] = config['timeout'] or '60'
result['method'] = config['method'] or 'rc4-md5'
"
把以下文件改名为index.htm替换/usr/lib/lua/luc/prometheus/index.htm。
[index.htm.zip](https://github.com/qiwihui/hiwifi-ss/files/1220425/index.htm.zip)
如果能改成类似

local method_list = {
	"table",
	"rc4",
	"rc4-md5",
	"aes-128-cfb",
	"aes-192-cfb",
	"aes-256-cfb",
	"bf-cfb",
	"camellia-128-cfb",
	"camellia-192-cfb",
	"camellia-256-cfb",
	"cast5-cfb",
	"des-cfb",
	"idea-cfb",
	"rc2-cfb",
	"seed-cfb",
	"salsa20",
	"chacha20",
	"chacha20-ietf",
}

method = basic:taboption("general", ListValue, "method", translate("Encryption Method"))
for _, value in ipairs(method_list) do method:value(value) end
method.default = "table"
method.rmempty = false
这样就可以选择而不需要手动输入。或有更好的办法。
来张图：
![1](https://user-images.githubusercontent.com/30280682/29249274-095ee350-805f-11e7-8331-fb0180797461.png)

### 期待SS 与 SSR 双版本共存。思路：借鉴大神的代码如下
	case "$vt_server" in
	shadowsocks)
		cat > $CONFIG_FILE <<EOF
{
	"server": "$vt_server_addr",
	"server_port": $vt_server_port,
	"local_address": "0.0.0.0",
	"password": "$vt_password",
	"timeout": 30,
	"method": "$vt_method"
}
EOF
	sleep 1
		/usr/bin/ss-redir -l$SS_REDIR_PORT -c$CONFIG_FILE -f $SS_REDIR_PIDFILE || return 1
		sleep 1
		if [ "$safe_dns_tcp" = 0 ]; then
		/usr/bin/ss-tunnel -c $CONFIG_FILE -l $safe_dns_port -L $safe_dns:$udp_pord -U -f $SS_REDIR_PIDFILE2 || return 1
		fi
		;;
	shadowsocksr)
		cat > $CONFIG_FILE <<EOF
{
	"server": "$server_addr",
	"server_port": $server_port,
	"local_address": "0.0.0.0",
	"password": "$password",
	"method": "$method",
	"timeout": 60,
	"protocol": "$protocol",
	"obfs": "$obfs",
	"obfs_param": "$obfs_param",
	"fast_open": false
}
EOF
	sleep 1
		/usr/bin/ssr-redir -l$SS_REDIR_PORT -c$CONFIG_FILE -f $SS_REDIR_PIDFILE || return 1
		sleep 1
		if [ "$safe_dns_tcp" = 0 ]; then
		/usr/bin/ssr-tunnel -c $CONFIG_FILE -l $safe_dns_port -L $safe_dns:$udp_pord -U -f $SS_REDIR_PIDFILE2 || return 1
		fi
		;;
	esac
