### ISSUE TITLE
有新版了1.4.5.19222s  升级了还用能吗？

### ISSUE THREAD

**Issue by qq1986114** [qiwihui/hiwifi-ss#140]
填写一下以下几个问题

1. 使用的 hiwifi-ss 版本

2. 问题产生过程

3. 你的期望

4. 运行结果

**Comment by huhai586** [comment]
新版功能正常就是样式文件加载404

发自我的 iPhone

**Comment by froer** [comment]
昨天刚升级了1.4.5.19222s，升级后ss的版面css有问题，但是墙还是可以翻的！！另外赶紧升级成SSR吧！！！！没有混淆间歇性抽风啊！！！！

**Comment by yyyyyyyhb** [comment]
同新版css抽了

**Comment by froer** [comment]
@huhai586 
升级1.4.5.19222s后，SS页面修复方法：
修改/usr/lib/lua/luci/view/admin_web/prometheus/index.html第13行
将：
<link rel="stylesheet" type="text/css" href="<%=resource%>/v2/style/net.css?v=<%=ver.svnRevNum%>">
改为：
<link rel="stylesheet" type="text/css" href="<%=resource%>/v2/style/admin_web/net.css?v=<%=ver.svnRevNum%>">

**Comment by huhai586** [comment]
@froer 谢谢，可以了
不过不是index.html 而是index.htm~

**Comment by zshleon** [comment]
我也遇到这个问题了，请问具体怎么修改呢？

**Comment by gaifeng8864** [comment]
我目前也遇到这个问题了，翻墙功能正常，就是页面不正常。

**Comment by Awx8** [comment]
极2升级到的是1.4.6.19458s，页面显示不正常，而且路由器会崩溃

**Comment by qiwihui** [comment]
最新版 v1.0.6 已修复了样式问题，欢迎使用。

谢谢 @froer 的修正。
