### ISSUE TITLE
求个在极路由上手动更新gw-shadowsocks.dnslist的方法

### ISSUE THREAD

**Issue by wurich614** [qiwihui/hiwifi-ss#142]
1. 使用的 hiwifi-ss 版本
v1.0.5 -- HC5962 - 1.3.5.18462s

2. 问题产生过程
不会更新gw-shadowsocks.dnslist

3. 你的期望
怎么手动更新gw-shadowsocks.dnslist

4. 运行结果
下载gfwlist2dnsmasq后 输入./gfwlist2dnsmasq.sh --port 53535 -o gw-shadowsocks.dnslist

提示缺少sed, base64, curl这些包 又opkg install coreutils-base64 curl ca-certificates 提示一堆

root@Hiwifi:/tmp# opkg install coreutils-base64 curl ca-certificates
Unknown package 'coreutils-base64'.
Package curl (7.38.0-1) installed in root is up to date.
Unknown package 'ca-certificates'.
Collected errors:
 * opkg_install_cmd: Cannot install package coreutils-base64.
 * opkg_install_cmd: Cannot install package ca-certificates.
Unknown package 'coreutils-base64'.
Package curl (7.38.0-1) installed in root is up to date.
Unknown package 'ca-certificates'.
Collected errors:
 * opkg_install_cmd: Cannot install package coreutils-base64.
 * opkg_install_cmd: Cannot install package ca-certificates.
Unknown package 'coreutils-base64'.
Package curl (7.38.0-1) installed in root is up to date.
Unknown package 'ca-certificates'.
Collected errors:
 * opkg_install_cmd: Cannot install package coreutils-base64.
 * opkg_install_cmd: Cannot install package ca-certificates.

**Comment by froer** [comment]
Windows10开启Linnux子系统：

1. • 系统升级到一周年正式版及以上(1607)
2. • 依次在设置-更新与安全-针对开发人员选项中，启用"开发人员模式"
3. • 在资源管理器中打开控制面板\所有控制面板项\程序和功能,打开"启用或关闭 Windows功能",勾选"适用于Linux的Windows子系统(Beta)"
4. • 重启电脑
5. • 命令行运行lxrun /install /y开始安装
6. 安装速度取决于网络情况，下载的文件在%localappdata%\lxss目录下lxss.tar.gz(181M)，解压后大概500M,rootfs目录即为子系统根目录。
7. 命令行运行bash进入Ubuntu

Linnux命令行下运行：
1. - git clone https://github.com/cokebar/gfwlist2dnsmasq.git
2. - cd gfwlist2dnsmasq
3. - ./gfwlist2dnsmasq.sh --port 53535 -o gw-shadowsocks.dnslist

拷贝C:\Users\“你的用户名”\gfwlist2dnsmasq\gw-shadowsocks.dnslist到/etc/gw-shadowsocks/和/etc/gw-redsocks/gw-shadowsocks两个目录下，覆盖同名文件。

**Comment by BenjaminX** [comment]
https://github.com/jndxhuxiehang/-dnslist-

**Comment by wurich614** [comment]
谢谢上面两位
