### ISSUE TITLE
不能依据教程卸载ss

### ISSUE THREAD

**Issue by huhai586** [qiwihui/hiwifi-ss#143]
填写一下以下几个问题

1. 使用的 hiwifi-ss 版本
 HC5861 - 1.4.5.19222s    

2. 问题产生过程
路由器上部署了ss，翻墙正常，但是本地pc上开启ss，就不能打开google，之前不是这样的，我想卸载后重新安装ss
3. 你的期望
卸载ss
4. 运行结果
找不到这句话里面说的index.html.ssbak

> 将/usr/lib/lua/luci/view/admin_web/network/index.htm.ssbak 重命名为 /usr/lib/lua/luci/view/admin_web/network/index.htm,

如果只执行opkg remove geewan-ss命令，路由器上的“”安全上网“”界面依然存在，重启不能消除

**Comment by wurich614** [comment]
不知道你ss什么版本的
老的版本修改文件是/usr/lib/lua/luci/view/admin_web/network/index.htm.ssbak
新版本的在侧面导航栏里 /usr/lib/lua/luci/view/admin_web/menu/menu_left.htm.ssbak
执行opkg remove geewan-ss

路由器开始ss 连上的设备都直接翻了啊 如果要省流量只用单个设备可以关了或卸载了

**Comment by qiwihui** [comment]
@huhai586 请参见 @wurich614 的方法。

**Comment by qiwihui** [comment]
thx @wurich614
