### ISSUE TITLE
gw-shadowsocks stop后弹出错误，页面的开关未显示关闭

### ISSUE THREAD

**Issue by wurich614** [qiwihui/hiwifi-ss#144]
1. 使用的 hiwifi-ss 版本
v1.0.5 -- HC5962 - 1.3.5.18462s

2. 问题产生过程
命令停止ss，有错误弹出，页面开关并没关闭（此时ss已经关闭了，状态显示未运行）

3. 你的期望
修复下哈，命令停止后开关显示关闭

4. 运行结果
root@Hiwifi:~# /etc/init.d/gw-shadowsocks stop
uci: Entry not found
会提示这样个错误，虽然安全上网的页面里的状态显示的是未运行，但开关显示的还是开

**Comment by qiwihui** [comment]
因为后台接口逻辑是lua脚本去更新状态，并执行`/etc/init.d/gw-shadowsocks` 的开启和停止，所以直接使用`/etc/init.d/gw-shadowsocks stop`是没法修改开关状态的。
