### ISSUE TITLE
SSR还不支持吗

### ISSUE THREAD

**Issue by zhenhappy** [qiwihui/hiwifi-ss#146]
我这边有编译好的二进制包，但是没有源码，不知道对你有没有帮助，需要的话我可以共享出来

**Comment by qq1986114** [comment]
这个是很需要的功能，希望能快些更新，没有混淆youtube经常断的，

**Comment by huhai586** [comment]
别人是非商业开发的，你们提问的时候建议前面加个"你好"

**Comment by froer** [comment]
@zhenhappy 
你说的是那个evenS吗？

**Comment by zhenhappy** [comment]
@froer 他那个我也有，不过他不更新了，我想自己开创一套版本，你有兴趣一起研究？我看你已经提了不少的PR了

**Comment by SouHong** [comment]
@zhenhappy 是3.2.8版本还是哪个版本？

**Comment by zhenhappy** [comment]
@SouHong 你指的版本是？

**Comment by SouHong** [comment]
@zhenhappy evenS文件夹中的shadowsocks.sh是否加M?如果没有可否分享？

**Comment by zhenhappy** [comment]
@SouHong 是有加密的，不过他加不加密其实无所谓，因为有程序在就可以手动运行命令也可以启动，不同代理模式和DNS模式处理直接抓命令行即可，总共5条命令，ss-local,ss-redir,scarred,还有两条一模一样的pdns的

**Comment by SouHong** [comment]
@zhenhappy 如果能与现在的版本结合可以使用不同的DNS模式可能会更兼容与稳定。

**Comment by zhenhappy** [comment]
有兴趣的话大家建一个Telegram的群交流交流

**Comment by SouHong** [comment]
@zhenhappy 你能把代理模式和DNS模式摸清楚就可以结合现在的版本了的。

[shadowsocks.zip](https://github.com/qiwihui/hiwifi-ss/files/1259476/shadowsocks.zip)

改名成shadowsocks.sh

**Comment by zhenhappy** [comment]
@SouHong 这个是已经加密的脚本，并没什么用

**Comment by froer** [comment]
evenS_SSR_3.2.8全文件备份，但是不知道全不全，大家一起研究下。

[evenS_SSR_B70_3.2.8_bak.zip](https://github.com/qiwihui/hiwifi-ss/files/1260396/evenS_SSR_B70_3.2.8_bak.zip)

**Comment by froer** [comment]
evenS_SSR_B70_3.2.8全文件备份，但是不知道全不全，可以一起研究下。
[evenS_SSR_B70_3.2.8_bak.zip](https://github.com/qiwihui/hiwifi-ss/files/1260405/evenS_SSR_B70_3.2.8_bak.zip)

**Comment by froer** [comment]
@zhenhappy 似乎不仅是命令，软件验证是通过http://hiwifiss.ml/lic.php?mac=xxxxxxx
SS服务的启动和停止好像需要ss_ajax.htm的response

**Comment by SouHong** [comment]
@froer 我期望能在现有的版本中丰富“代理模式和DNS模式”
https://github.com/SouHong/hiwifi-ss/tree/ss-ssr

**Comment by zhenhappy** [comment]
@froer 那些都是GUI交互的问题，没有界面通过命令行能启动的话就成功一半了，剩下界面交互问题都比较简单, @SouHong 你现在这个分支进度是如何了，代理和DNS是分开的两个功能，之间没有直接联系

**Comment by SouHong** [comment]
@zhenhappy HC5962使用暂没有问题。GFW列表模式与全局可选，S与SR可选。希望后期能再添加代理模式与DNS模式。

**Comment by zhenhappy** [comment]
@SouHong @froer 到Telegram上加我吧，我建个群大家一起讨论
