### ISSUE TITLE
hiwifi-ss 无法运行一直转圈

### ISSUE THREAD

**Issue by bonejovi** [qiwihui/hiwifi-ss#147]
填写一下以下几个问题

1. 使用的 hiwifi-ss 版本
cd /tmp && curl -k -o shadow.sh https://raw.githubusercontent.com/qiwihui/hiwifi-ss/master/shadow.sh && sh shadow.sh && rm shadow.sh
v1.0.5
2. 问题产生过程
hiwifi4 HC5962 
固件版本1.3.5.18462s 成功安装，但是在ss那个界面中开关打开一直转圈，状态显示未运行，始终连接不上服务器，服务器我在电脑端都可以使用，降级固件至1.2.5.15805s后，也是同样问题，求解。

**Comment by froer** [comment]
@bonejovi 用chrome打开管理页面，相关ss页面的css似乎和原版文件有冲突。

**Comment by bonejovi** [comment]
果然是浏览器不兼容的问题，用chrome打开就可以开启了，谢谢提醒

**Comment by qiwihui** [comment]
样式问题在v1.0.6版本中修复了，可以更新试试
