### ISSUE TITLE
建议支持直接通过ss服务端口进行代理访问

### ISSUE THREAD

**Issue by binsee** [qiwihui/hiwifi-ss#149]
填写一下以下几个问题

1. 使用的 hiwifi-ss 版本
hiwifi-ss v1.0.5
B70 - 1.3.5.18462s

2. 问题产生过程

有时会遇到希望让指定网站走ss访问，通过chrome的SwichyOmega插件来直接指定通过sock5: 192.168.199.1: 16080 来使访问直接走ss，而不经过路由器端的路由判断。但却导致任何网站都无法访问

经过排查后发现是`/etc/init.d/gw-shadowsocks` 脚本中`service_start /usr/bin/ss-local -s $server -p $server_port -l $local_port` 没有使用 `-b 0.0.0.0`参数，`-b` 参数用来指定ss监听本地服务的ip，默认是`127.0.0.1`，也就是只能让路由器自身来访问，需要指定`0.0.0.0`来让局域网中其他设备可以访问本地监听端口

3. 你的期望

增加`-b 0.0.0.0`参数，以支持其他设备直接访问ss
目前我是手动改了参数在用，如果其他人有同类需求，那还是直接改项目的默认脚本更为合适。

**Comment by hasateks** [comment]
有同样的需要，但是我不会改

**Comment by qiwihui** [comment]
@binsee 欢迎提交 Pull request

**Comment by binsee** [comment]
之前提交过pr #153 ，通过添加更多设置选项方式进行了支持。
