### ISSUE TITLE
无法访问google、youtube等网站

### ISSUE THREAD

**Issue by Chadwick97** [qiwihui/hiwifi-ss#15]
#### 问题描述
第一次安装，应该安装成功了。配置了ss后，选的智能模式和谷歌DNS。国外很多网站可以正常访问，但是google和youtube却不行，提示找不到google.com的DNS地址，这怎么解决呢？

另外全局模式ss配置就无法正常运行了，一遍遍地刷新、重启都不行，无法联网

**Comment by Chadwick97** [comment]
抱歉，是我电脑的host的问题，已经解决。打扰了

**Comment by qiwihui** [comment]
😄没关系的，互相交流！
