### ISSUE TITLE
[已解决]极路由4自动升级固件到 HC5962 - 1.4.5.19222s 后 hiwifi-ss无法安装使用

### ISSUE THREAD

**Issue by jimyang2008** [qiwihui/hiwifi-ss#150]
填写一下以下几个问题

## 1. 使用的 hiwifi-ss 版本

目前最新版本 v1.0.6

## 2. 问题产生过程

2台极路由
* 极路由4 HC5962 
* 极路由 B70

都在自动升级固件**1.4.5.19222s**后，命令行安装shadowsocks插件没问题，但界面上没有Shadowsocks的按键出现，无法配置使用。

## 3. 你的期望

希望能够在HC5962 或 B70 的固件版本 **1.4.5.19222s** 上继续使用 hiwifi-ss，非常感谢

## 4. 运行结果

试图使用readme里 新的和旧的脚本都不成功

**Comment by jimyang2008** [comment]
在B70里发现界面跑到最下面的又一个**安全上网**里面了，虽然貌似css style有点乱，但亲测可用。

**Comment by jimyang2008** [comment]
Leave it open so that others can see it

**Comment by xinyuandd** [comment]
![image](https://user-images.githubusercontent.com/3397848/29910195-965cd316-8e5b-11e7-819d-2bf80c3b3db4.png)

**Comment by wujunze** [comment]
我的极路由1S也遇到了CSS样式文件  加载失败的问题  但是功能是正常的

**Comment by LiLejia** [comment]
应该把 `<link rel="stylesheet" type="text/css" href="<%=resource%>/v2/style/net.css?v=<%=ver.svnRevNum%>">`改为`<link rel="stylesheet" type="text/css" href="<%=resource%>/v2/style/admin_web/net.css?v=<%=ver.svnRevNum%>">`

**Comment by JefferyWang** [comment]
赞👍

**Comment by wujunze** [comment]
@LiLejia   你好  请问在哪个目录下面改?  是改已经安装好的吗?  还是改完之后重新安装一次?

**Comment by q629988171** [comment]
![hiwifi-ss_admin_web](https://user-images.githubusercontent.com/2260447/30240818-1c2bac60-95aa-11e7-84e6-237b45891142.png)

改已经安装好的

**Comment by wujunze** [comment]
已经安装好的路径是什么？  在哪个目录下@

**Comment by LiLejia** [comment]
截图上有啊，朋友们，`/usr/lib/lua/luci/view/admin_web/prometheus/index.htm`。

**Comment by wujunze** [comment]
好的  谢谢 @LiLejia

**Comment by gaifeng8864** [comment]
我的系统版本 : HC5661 - 1.4.5.19222s，安装后也有这个问题，改过之后显示倒是正常了，但是功能不能用。

**Comment by AlexLai02** [comment]
互联网界面一直在转圈，求解

**Comment by madderhuang** [comment]
【1】】极路由B50-MT7620A-1.4.6.19458s-安装ss成功。插件主要看CPU，不用管HCXXXX
----------------------------------------------------------------
【2】完美解决所有CSS加载问题：互联网  和  SS 安全上网   页面
-----------------------------------------------------------------
【3】修改地方
（0）用winscp连接路由器。模式SCP；端口1022；账号：默认一般为root；密码：你登录路由器后台的密码
（1）SS【安全上网】css修改 
打开  /usr/lib/lua/luci/view/admin_web/prometheus/index.htm 文件
把 <link rel="stylesheet" type="text/css" href="<%=resource%>/v2/style/net.css?v=<%=ver.svnRevNum%>">
修改为
<link rel="stylesheet" type="text/css" href="<%=resource%>/v2/style/admin_web/net.css?v=<%=ver.svnRevNum%>">
（2）【互联网】css修改 
打开  /usr/lib/lua/luci/view/admin_web/network/index.htm
把  <link rel="stylesheet" type="text/css" href="<%=resource%>/v2/style/admin_web/net.css?v=<%=ver.svnRevNum%>">
修改为
<link rel="stylesheet" type="text/css" href="<%=resource%>/v2/style/admin_web/net.css?v=<%=ver.svnRevNum%>">

**Comment by madderhuang** [comment]
【1】】极路由B50-MT7620A-1.4.6.19458s-安装ss成功。插件主要看CPU，不用管HCXXXX
----------------------------------------------------------------
【2】完美解决所有CSS加载问题：互联网  和  SS 安全上网   页面
-----------------------------------------------------------------
【3】修改地方
-----------------------------------------------------------------
（0）用winscp连接路由器。模式SCP；端口1022；账号：默认一般为root；密码：你登录路由器后台的密码
（1）SS【安全上网】css修改 
打开  /usr/lib/lua/luci/view/admin_web/prometheus/index.htm 文件
把 <%=resource%>/v2/style/net.css?v=<%=ver.svnRevNum%>
修改为  <%=resource%>/v2/style/admin_web/net.css?v=<%=ver.svnRevNum%>
（2）【互联网】css修改 
打开  /usr/lib/lua/luci/view/admin_web/network/index.htm
把  <%=resource%>/v2/style/admin_web/net.css?v=<%=ver.svnRevNum%>
修改为  <%=resource%>/v2/style/admin_web/net.css?v=<%=ver.svnRevNum%>

**Comment by madderhuang** [comment]
【1】】极路由B50-MT7620A-1.4.6.19458s-安装ss成功。插件主要看CPU，不用管HCXXXX
----------------------------------------------------------------
【2】完美解决所有CSS加载问题：互联网  和  SS 安全上网   页面
-----------------------------------------------------------------
【3】修改地方
-----------------------------------------------------------------
（0）用winscp连接路由器。模式SCP；端口1022；账号：默认一般为root；密码：你登录路由器后台的密码
（1）SS【安全上网】css修改 
打开  /usr/lib/lua/luci/view/admin_web/prometheus/index.htm 文件
把         <%=resource%>/v2/style/net.css?v=<%=ver.svnRevNum%>
修改为  <%=resource%>/v2/style/admin_web/net.css?v=<%=ver.svnRevNum%>
（2）【互联网】css修改 
打开  /usr/lib/lua/luci/view/admin_web/network/index.htm 文件
把         <%=resource%>/v2/style/net.css?v=<%=ver.svnRevNum%>
修改为  <%=resource%>/v2/style/admin_web/net.css?v=<%=ver.svnRevNum%>

**Comment by ffantasyd** [comment]
怎么安装1.0.6版本？我用命令行只能装到1.0.5版本，怎么升级

**Comment by woaixiangbao** [comment]
真好，按照@madderhuang 的方法修改了样式表的路径，现在界面已经好了。
如果还有不知道怎么修改的同学，是不是不知道怎么从命令行里登陆极路由的后台啊？Mac下的登陆方法是：ssh root@192.168.199.1 -p 1022

![image](https://user-images.githubusercontent.com/1953879/31020299-2f9546a0-a4f8-11e7-9b2a-b069222d6e6f.png)

**Comment by zboys** [comment]
安装好后我的本地端口修改不了？怎么解决

**Comment by qiwihui** [comment]
@zboys 本地端口不支持更改

**Comment by qiwihui** [comment]
@jimyang2008 最新版v1.0.6已修正样式问题

谢谢大家的支持。
