### ISSUE TITLE
极路由4自动升级固件到 HC5962 - 1.4.5.19222s 后 无法启动

### ISSUE THREAD

**Issue by LPegasus** [qiwihui/hiwifi-ss#156]
## 1. 使用的 hiwifi-ss 版本
v1.0.5

## 2. 问题产生过程
升级固件后重新按照readme中的步骤安装并重启路由器

## 3. 你的期望
正常运行

## 4. 运行结果
1. 界面状态一直显示未运行
2. 运行 `/lib/gw-shadowsocks.sh status` 显示 `stopped`

**Comment by LPegasus** [comment]
![图](https://user-images.githubusercontent.com/12448145/30606828-96b430d0-9da5-11e7-90f3-7b70468c74a5.png)

**Comment by Blackcurrant** [comment]
你的问题解决了吗？

**Comment by qiwihui** [comment]
试试v1.0.6版本，直接使用命令安装就可以了
