### ISSUE TITLE
b70 升级固件1.4.5后不支持ss配置了

### ISSUE THREAD

**Issue by KaapoMarcus** [qiwihui/hiwifi-ss#157]
填写一下以下几个问题

1. 系统版本 : B70 - 1.4.5.19222s

2. 互联网菜单 ----页面样式错乱，切无法打开配置文件

**Comment by FengkuiChan** [comment]
发帖前先浏览历史issues，这个问题已经有解决办法，主要是css的路径出错了。

**Comment by qiwihui** [comment]
最新版 v1.0.6 已修正
