### ISSUE TITLE
v1.0.5版本如何升级到v1.0.6以及udp转发问题

### ISSUE THREAD

**Issue by ffantasyd** [qiwihui/hiwifi-ss#158]
填写一下以下几个问题

1. 使用的 hiwifi-ss 版本
v1.0.5
2. 问题产生过程
看到有新版的v1.0.6的ss，请问如何升级，另外udp转发功能实属摆设，并不能有效使用，什么时候能实现呀！！
3. 你的期望
升级至v1.0.6，实现udp转发
4. 运行结果

**Comment by gaifeng8864** [comment]
得自己编译安装。

**Comment by q629988171** [comment]
@gaifeng8864 直接覆盖就行

**Comment by gaifeng8864** [comment]
哦？把那三个文件夹直接覆盖到路由器上的文件夹吗？

**Comment by q629988171** [comment]
@gaifeng8864 看文件更新记录，如果觉得麻烦就整个下载进行覆盖

**Comment by Roger1219** [comment]
cd /tmp && curl -k -o shadow.sh https://raw.githubusercontent.com/qiwihui/hiwifi-ss/master/shadow.sh && sh shadow.sh && rm shadow.sh
ssh路由器后，运行以上代码成功，但是没感觉更新了呀

**Comment by gaifeng8864** [comment]
@Roger1219 确实没有更新。脚本下载的是releases里的文件。

**Comment by qiwihui** [comment]
已更新了v1.0.6版本。
