### ISSUE TITLE
请问如何ssh到路由器？

### ISSUE THREAD

**Issue by arthasgxy** [qiwihui/hiwifi-ss#159]
原谅我比较小白，刚买上极路由3s
固件版本：C312A - 1.4.5.19222s
ssh 192.168.199.1 -p1022 -lroot
ssh: connect to host 192.168.199.1 port 1022: Connection refused

根本连不上。。。
难道我要怎么样来打开路由器上的1022端口？还是怎么样？

由于README直接跳过了ssh的步骤，而在网上又根本搜不到相关的信息。。（国内全都是说刷固件的）
故有此一问，还请见谅。

**Comment by q629988171** [comment]
@arthasgxy 访问app.hiwifi.com首页->选中要申请的路由器-> 路由器信息->高级设置->”+”->申请（开通开发者模式）->同意各种条款->结束。
安装开发者模式插件之后，就可以以root身份ssh进入路由。

**Comment by arthasgxy** [comment]
@q629988171 好的，非常感谢了。
看到要手持身份证的正面照，果断放弃了。。。

**Comment by q629988171** [comment]
@arthasgxy 现在这麻烦，还有另外一个办法，不过我没有试过，就是安装ROOT插件

**Comment by arthasgxy** [comment]
@q629988171 好的，我试试。非常感谢
