### ISSUE TITLE
安装错误提示如下：luci-cache does not exist

### ISSUE THREAD

**Issue by i7worlds** [qiwihui/hiwifi-ss#16]
#### 问题描述

请教……～ 按说明操作遇到安装错误提示如下：luci-cache does not exist! 无法找到luci-cache,请确定是否是极路由环境。
#### 运行结果

重启后在后台页面有SS导航菜单，但是点击跳出“文件未找到... ”。所用的型号为极路由3 系统版本：HC5861 - 1.0.7.13499s 。候教……谢谢！

**Comment by qiwihui** [comment]
@i7worlds 遇到 `luci-cache does not exist! 无法找到luci-cache,请确定是否是极路由环境` 可以忽略，这个是脚本遗留问题；

然后你遇到的 `文件未找到... ` 问题我不是很确定，可能是安装时网络影响了安装，你试着重新安装一次试试。

**Comment by qiwihui** [comment]
fixed by c4064a7223f644dfebd10a08be273a199acb5a47
