### ISSUE TITLE
UI界面不能正常显示，排版错乱

### ISSUE THREAD

**Issue by xiurui12345** [qiwihui/hiwifi-ss#161]
1. 使用的 hiwifi-ss 版本
系统版本 : HC5661A - 1.4.5.19222s 
2. 问题产生过程
UI界面不能正常显示，排版错乱
![111](https://user-images.githubusercontent.com/1821298/30974676-c606d564-a4a2-11e7-9565-c39de175be89.png)

3. 你的期望
安装的是最新版本1.0.5，通过命令远程安全，提示安装成功。

**Comment by gumutianqi** [comment]
我的也是一样的错乱：
版本：HC5861 - 1.4.5.19222s
如下图：

![default](https://user-images.githubusercontent.com/1057589/31078984-c32bbd6a-a749-11e7-8ef9-1664ef80ba56.jpg)

**Comment by TOMBFIRE** [comment]
ssh连进路由器，手动将/usr/lib/lua/luci/view/admin_web/prometheus/index.htm中的
<link rel="stylesheet" type="text/css" href="<%=resource%>/v2/style/net.css?v=<%=ver.svnRevNum%>">
更换为
<link rel="stylesheet" type="text/css" href="<%=resource%>/v2/style/admin_web/net.css?v=<%=ver.svnRevNum%>">

**Comment by hotter909** [comment]
@TOMBFIRE  的解决方案非常有效，修改后直接恢复正常。

**Comment by qiwihui** [comment]
已在最新版v1.0.6修正
