### ISSUE TITLE
排版好像除了问题

### ISSUE THREAD

**Issue by leoxu1007** [qiwihui/hiwifi-ss#165]
填写一下以下几个问题

1. 使用的 hiwifi-ss 版本
刚刚下载的最新版本v1.0.5
2. 问题产生过程
页面排版除了问题，前几个按钮都是好的，但是点击ss之后排版就坏掉了。

3. 你的期望

4. 运行结果
![0029-10-18 4 00 04](https://user-images.githubusercontent.com/22413258/31707230-49a56800-b3b1-11e7-8e3c-77ea3e8a6ab7.png)
![0029-10-18 3 59 55](https://user-images.githubusercontent.com/22413258/31707238-507f92a4-b3b1-11e7-8204-7928d5c73d44.png)

btw鼠标浮在上面的时候不会显示小飞机图标。

**Comment by leoxu1007** [comment]
![0029-10-28 9 46 54](https://user-images.githubusercontent.com/22413258/32134954-a0edcc7a-bbbc-11e7-8999-ee33536efac0.png)
![0029-10-28 9 47 05](https://user-images.githubusercontent.com/22413258/32134956-a2b6b49a-bbbc-11e7-9b7c-53ae2e2854ef.png)

就想这样。倒是能运行，但是出现了排版崩坏

**Comment by FengkuiChan** [comment]
需要对/usr/lib/lua/luci/view/admin_web/prometheus/index.htm 文件进行修改。

1、SSH连接极路由

2、输入命令：vim /usr/lib/lua/luci/view/admin_web/prometheus/index.htm

3、按“i”，开始修改代码
1）找到：<link rel="stylesheet" type="text/css" href="<%=resource%>/v2/style/net.css?v=<%=ver.svnRevNum%>">
2）在“style/”后添加“admin_web/”
3）即：<link rel="stylesheet" type="text/css" href="<%=resource%>/v2/style/admin_web/net.css?v=<%=ver.svnRevNum%>">

4、保存修改内容
1）Esc
2）:wq

4、刷新极路由后台管理页面即可

**Comment by FengkuiChan** [comment]
找到：link rel="stylesheet" type="text/css" href="<%=resource%>/v2/style/net.css?v=<%=ver.svnRevNum%>"

**Comment by honeyjim** [comment]
thanks ..i got the same problem...i found that the path is not correct ..should add admin_web directory.

**Comment by qiwihui** [comment]
最新版已修正。
