### ISSUE TITLE
1.2.5.15805s如何添加chacha20-ietf-poly1305加密方式？

### ISSUE THREAD

**Issue by andoumasaki** [qiwihui/hiwifi-ss#167]
路由器版本HC5861 - 1.2.5.15805s 

加密列表中没有chacha20-ietf-poly1305

请问如何添加？

**Comment by q629988171** [comment]
@andoumasaki 升级hiwifi-ss到 1.5版本

**Comment by 351zyf** [comment]
1.5 ? 这里不是指维护到了1.05吗？

**Comment by 351zyf** [comment]
看错了  我发现有新算法了

**Comment by qiwihui** [comment]
谢谢 @q629988171 的解释。
