### ISSUE TITLE
V1.0.5无法运行

### ISSUE THREAD

**Issue by LYH-inori** [qiwihui/hiwifi-ss#169]
填写一下以下几个问题

1. 使用的 hiwifi-ss 版本
HC5861 - 1.4.5.19222s 

v1.0.5
--
2. 问题产生过程
状态一直未运行，而且无法保存配置，一刷新就清空

![qq 20171104210122](https://user-images.githubusercontent.com/28772072/32405607-8d2f723c-c1a3-11e7-94f1-ed3b9d3c6946.jpg)

刷新后
![qq 20171104210146](https://user-images.githubusercontent.com/28772072/32405608-96b7ea46-c1a3-11e7-9d66-4544cd2d9dc6.jpg)

**Comment by qiwihui** [comment]
这个在最新版v1.0.6已修复了，你填好了配置保存之后再刷新试试。
