### ISSUE TITLE
提示git not found怎么解决

### ISSUE THREAD

**Issue by FengkuiChan** [qiwihui/hiwifi-ss#171]
填写一下以下几个问题

1. 使用的 hiwifi-ss 版本

v1.05

2. 问题产生过程

在使用项目 gfwlist2dnsmasq 中的脚本“git clone https://github.com/cokebar/gfwlist2dnsmasq.git”更新dnsmasq.conf过程中，提示：-ash: git: not found

3. 你的期望

希望能够更新dnsmasq.conf

4. 运行结果

返回值：-ash: git: not found

**Comment by AmazingSS** [comment]
退出极路由的 ssh 连接，在你本地的环境中执行 git，获取gw-shadowsocks.dnslist后，通过 scp 命令上传到极路由。
scp -P 1022 gw-shadowsocks.dnslist root@192.168.199.1:/etc/gw-shadowsocks/gw-shadowsocks.dnslist

**Comment by FengkuiChan** [comment]
谢谢。
