### ISSUE TITLE
极路由4增强版修改sid安装ss插件后，路由器变为离线状态

### ISSUE THREAD

**Issue by huochequan** [qiwihui/hiwifi-ss#173]
填写一下以下几个问题

1. 使用的 hiwifi-ss 版本
用sid安装的ss插件
2. 问题产生过程
ss插件安装好后，路由器离线，无法进入插件页面
3. 你的期望
期望能正常运行ss插件
4. 运行结果

**Comment by q629988171** [comment]
@huochequan 通过SID安装SS插件属于官方市场不在本项目讨论范围，如果你是在官方市场安装的话；

**Comment by qiwihui** [comment]
谢谢 @huochequan 的解释。
