### ISSUE TITLE
好像有1个文案和1个css路径bug

### ISSUE THREAD

**Issue by gMan1990** [qiwihui/hiwifi-ss#174]
1、hiwifi-ss/shadow.sh
12行    echo ">1.2.5.15805s"      下面else也是这样提示的。。
2、hiwifi-ss/usr/lib/lua/luci/view/admin_web/prometheus/index.htm
<link rel="stylesheet" type="text/css" href="<%=resource%>/v2/style/net.css?v=<%=ver.svnRevNum%>">
应该是style/admin_web/net.css

**Comment by qiwihui** [comment]
已在v1.0.6版本中修复，请重新下载安装
