### ISSUE TITLE
HC5861 - 1.4.5.19222 样式缺失

### ISSUE THREAD

**Issue by zyltd1990** [qiwihui/hiwifi-ss#179]
填写一下以下几个问题

1. 使用的 hiwifi-ss 版本
HC5861 - 1.4.5.19222

2. 问题产生过程
安装完成，出现安全上网，点进去以后缺少样式
3. 你的期望

4. 运行结果
![1](https://user-images.githubusercontent.com/12107185/33522764-3b033b68-d82f-11e7-8912-42c8e569fb6c.PNG)

**Comment by demonk** [comment]
5831 在 19222 上能使用吗？

**Comment by imalandu** [comment]
缺失文件为：net.css
可以从 /www/turbo-static/turbo/v2/style/admin_web/net.css复制到/www/turbo-static/turbo/v2/style/目录下，刷新页面即可
亲测有效

**Comment by cyrilkong** [comment]
@imalandu 修正成功！谢了

**Comment by hidetag** [comment]
执行`busybox`命令   ->  ` /www/turbo-static/turbo/v2/style/admin_web# cp net.css /www/turbo-st
atic/turbo/v2/style/net.css`

**Comment by qiwihui** [comment]
已在最新版v1.0.6修正
