### ISSUE TITLE
反馈一个问题,安装以后在手机逛淘宝图片显示会变得很慢

### ISSUE THREAD

**Issue by cyleonebk** [qiwihui/hiwifi-ss#18]
#### 问题描述
安装后哪怕是关闭服务,使用ios的手机淘宝图片显示会很慢.PC浏览没问题. 手动删除无效.必须要恢复出厂设置.

**Comment by qiwihui** [comment]
请问你指的慢是何种程度的慢？使用前和使用后有具体数据对比吗？有其他网站也输这种情况吗？

**Comment by cyleonebk** [comment]
我觉得应该gfw-list的问题,类似图片从国外加载的那种感觉,复位路由器后才解决.
