### ISSUE TITLE
HC5661A - 1.4.5.19222s 

### ISSUE THREAD

**Issue by yuchenshuize** [qiwihui/hiwifi-ss#180]
填写一下以下几个问题

1. 使用的 hiwifi-ss 版本 
 HC5661A - 1.4.5.19222s 

2. 问题产生过程  
安装新版hiwifi的安全上网，点击安全上网出现问题

3. 你的期望 
正常运行

4. 运行结果 
出现样式缺少，且显示连接错误，不知DMZ是否影响，以及chacha20加密是否可以使用，采用SS销售商的SS，确认采用chacha20的SS可用

**Comment by ykla** [comment]
同样出现连接错误

**Comment by imalandu** [comment]
缺失文件为：net.css
可以从 /www/turbo-static/turbo/v2/style/admin_web/net.css复制到/www/turbo-static/turbo/v2/style/目录下，刷新页面即可
亲测有效

**Comment by steven64521** [comment]
@imalandu 多谢，复制net.css文件之后样式就恢复正常了

**Comment by qiwihui** [comment]
resolved in v1.0.6
