### ISSUE TITLE
怎么安装hiwifi-ss 1.0.6

### ISSUE THREAD

**Issue by FengkuiChan** [qiwihui/hiwifi-ss#181]
填写一下以下几个问题

1. 使用的 hiwifi-ss 版本
1.0.5
2. 问题产生过程
在智能模式下，有些网站会走错路线
3. 你的期望
想试试v1.0.6
4. 运行结果

**Comment by froer** [comment]
@FengkuiChan 
https://github.com/qiwihui/hiwifi-ss/issues/178

**Comment by FengkuiChan** [comment]
@froer 谢谢你。按照你提供的编译包和防范安装后，发现一个问题：智能模式无法科学上网，全局模式可以。请问你的智能模式使用正常吗？

**Comment by froer** [comment]
@FengkuiChan 
脚本是每周三更新china-banned和gfwlist，你也可以随时手动发起更新，运行：
etc/gw-shadowsocks/upgfwlist.sh
etc/gw-shadowsocks/upchinaroute.sh

**Comment by FengkuiChan** [comment]
@froer 我今晚回家更新一下试试看。

**Comment by FengkuiChan** [comment]
@froer 我重装并更新了GFW list等规则，智能模式还是无法正常使用，全局可以。

**Comment by froer** [comment]
@FengkuiChan 不清楚了，我一直用着是没问题的

**Comment by FengkuiChan** [comment]
@froer 我的也是HC5962，不过固件是最新的1.4.5.19222s

**Comment by froer** [comment]
@FengkuiChan 你之前装过其他版本的ss吗？如果装过最后恢复出厂设置再装这个1.0.6试下。
