### ISSUE TITLE
如何静态编译适用于极路由5962的shadowsocks-libev 3.1.2？

### ISSUE THREAD

**Issue by froer** [qiwihui/hiwifi-ss#187]
如何静态编译适用于极路由5962的shadowsocks-libev 3.1.2？
https://haoutil.com/topic/cross-compile-shadowsocks-libev
不懂啊，求教！

**Comment by froer** [comment]
折腾一晚上，搞成了！
[Shadowsocks-libev_v3.1.2_for_HC5962.zip](https://github.com/qiwihui/hiwifi-ss/files/1597853/Shadowsocks-libev_v3.1.2_for_HC5962.zip)

附笔记：

极路由SDK下载：http://sdk.ikcd.net/mtmips-sdk.tar.bz2

-----------下载
apt-get install -y build-essential autoconf autopoint automake git pkg-config libtool

cd /mnt
wget http://sdk.ikcd.net/mtmips-sdk.tar.bz2
tar jxvf mtmips-sdk.tar.bz2
mv OpenWrt-SDK-mtmips-for-redhat-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2 hc5962


-----------调整编译环境
MLIB=mipsel
TOOLCHAINDIR=/mnt/hc5962/staging_dir
TOOLCHAIN=$TOOLCHAINDIR/toolchain-mipsel_24kec_gcc-4.8-linaro_uClibc-0.9.33.2
HOST=${MLIB}-openwrt-linux
PATH_A=$PATH
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
PATH=$TOOLCHAIN/bin:$PATH

完成后运行$HOST-gcc -v；返回版本信息说明交叉编译工具配置正常
$HOST-gcc -v


-----------创建编译目录
rm -rf /mnt/build/shadowsocks-$MLIB
mkdir -p /mnt/build/shadowsocks-$MLIB && cd /mnt/build/shadowsocks-$MLIB
BASE=`pwd`
SRC=$BASE/src
PREFIX=$BASE/local
PRE=$BASE/lib
mkdir -p $SRC $PRE $PREFIX
PKG_CONFIG_PATH=$PRE/lib/pkgconfig/
LD_LIBRARY_PATH=$PRE/lib/

export STAGING_DIR=/mnt/hc5962/staging_dir


------------编译mbedTLS
mkdir $SRC/mbedTLS && cd $SRC/mbedTLS
ver=2.6.0
wget --no-check-certificate https://tls.mbed.org/download/mbedtls-$ver-gpl.tgz
tar zxf mbedtls-$ver-gpl.tgz
cd mbedtls-$ver
CC=$HOST-gcc AR=$HOST-ar LD=$HOST-ld LDFLAGS=-static make DESTDIR=$PREFIX install


------------编译pcre
mkdir $SRC/pcre && cd $SRC/pcre
ver=8.41
wget ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre-$ver.tar.gz
tar zxf pcre-$ver.tar.gz
cd pcre-$ver
./configure --host=$HOST --prefix=$PREFIX --disable-shared --enable-utf8 --enable-unicode-properties
make -j`nproc` && make install


------------编译libsodium
mkdir $SRC/libsodium && cd $SRC/libsodium
ver=1.0.16
wget --no-check-certificate https://download.libsodium.org/libsodium/releases/libsodium-$ver.tar.gz
tar zxf libsodium-$ver.tar.gz
cd libsodium-$ver
./configure --host=$HOST --prefix=$PREFIX --disable-ssp --disable-shared
make -j`nproc` && make install


------------编译libev
mkdir $SRC/libev && cd $SRC/libev
ver=4.24
wget http://dist.schmorp.de/libev/libev-$ver.tar.gz
tar zxf libev-$ver.tar.gz
cd libev-$ver
./configure --host=$HOST --prefix=$PREFIX --disable-shared
make -j`nproc` && make install

------------编译libudns
mkdir $SRC/libudns && cd $SRC/libudns
git clone git://github.com/shadowsocks/libudns
cd libudns
./autogen.sh
./configure --host=$HOST --prefix=$PREFIX
make -j`nproc` && make install

------------编译c-ares
mkdir $SRC/c-ares && cd $SRC/c-ares
ver=1.13.0
wget https://c-ares.haxx.se/download/c-ares-$ver.tar.gz
tar zxvf c-ares-$ver.tar.gz
cd c-ares-$ver
sed -i 's#\[-\]#[1.13.0]#' configure.ac
./buildconf
./configure --prefix=$PREFIX --host=$HOST CC=$HOST-gcc --enable-shared=no --enable-static=yes
make -j`nproc` && make install

------------编译shadowsocks-libev
mkdir $SRC/shadowsocks-libev && cd $SRC/shadowsocks-libev
ver=3.1.2
git clone git://github.com/shadowsocks/shadowsocks-libev
cd shadowsocks-libev
git checkout v$ver -b v$ver
git submodule init && git submodule update
./autogen.sh
LIBS="-lpthread -lm" LDFLAGS="-Wl,-static -static -static-libgcc -L$PREFIX/lib" CFLAGS="-I$PREFIX/include"  ./configure --host=$HOST --prefix=$PREFIX --disable-ssp --disable-documentation --with-mbedtls=$PREFIX --with-pcre=$PREFIX --with-sodium=$PREFIX
make -j`nproc` && make install

------------编译simple-obfs
mkdir $SRC/simple-obfs && cd $SRC/simple-obfs
ver=0.0.5
git clone https://github.com/shadowsocks/simple-obfs
cd simple-obfs
git checkout v$ver -b v$ver
git submodule init && git submodule update
./autogen.sh
LIBS="-lpthread -lm" LDFLAGS="-Wl,-static -static -static-libgcc -L$PREFIX/lib" CFLAGS="-I$PREFIX/include" \
	./configure --host=$HOST --prefix=$PREFIX --disable-ssp --disable-documentation
make -j`nproc` && make install

------------压缩体积
cp $PREFIX/bin/ss-* $BASE
cp $PREFIX/bin/obfs-* $BASE
$HOST-strip $BASE/obfs-*
$HOST-strip $BASE/ss-*
cd $BASE

------------还原环境变量
PATH=$PATH_A
echo
echo "Done!"

**Comment by FengkuiChan** [comment]
厉害

**Comment by FengkuiChan** [comment]
请问怎样安装插件呢

**Comment by FengkuiChan** [comment]
期待安装包

**Comment by qiwihui** [comment]
thanks @froer

**Comment by Paull** [comment]
@froer 往照你这个脚本走，在shadowsocks-libev的./configure那步，会提示
```
checking for pthread-config... no
configure: error: Can not find pthreads.  This is required.
```
不知道是不是要特定版本还是怎样

**Comment by paicha** [comment]
麻烦方便的话，能否放出一个 ss-server ？

**Comment by paicha** [comment]
3.1.2 死活报错，编译了一个 3.0.2 版本的 ss-server 
[ss-server-3.0.2.zip](https://github.com/qiwihui/hiwifi-ss/files/1770722/ss-server-3.0.2.zip)

**Comment by Paull** [comment]
你留个邮箱我发你，或者脚本给你自己编译，不过编译肯定还要看实际环境稍作修改

2018年3月1日 下午3:53，"Gary" <notifications@github.com>写道：

**Comment by paicha** [comment]
谢谢，我已经编译好了，相应文件回复在上文了。
Paul Liu <notifications@github.com>于2018年3月1日 周四下午7:23写道：

**Comment by dreamyphone** [comment]
@Paull 你编译的3.0.2在你的环境下能运行吗？我运行只能输出帮助信息。

**Comment by Paull** [comment]
有帮助输出不就行了吗？加对参数就可以跑了。

dreamyphone <notifications@github.com> 于 2018年6月14日周四 11:21写道：

**Comment by dreamyphone** [comment]
@Paull 问题是加任何参数都是一样的结果，只能打印帮助信息，不能做任何事情

**Comment by dreamyphone** [comment]
@froer 楼主，我在编译编译shadowsocks-libev的时候报错提示如下错误，有遇到过吗？

> checking for ev.h... yes
>checking libev/ev.h usability... no
>checking libev/ev.h presence... no
>checking for libev/ev.h... no
>checking for ev_loop_destroy in -lev... no
>configure: error: Couldn't find libev. Try installing libev-dev[el].

**Comment by dreamyphone** [comment]
楼主如果方便，麻烦给我发一个编译好的ss-server可以吗？
dreamyphone@gmail.com
