### ISSUE TITLE
开启混淆模式后 显示未运行

### ISSUE THREAD

**Issue by ilovebamboo** [qiwihui/hiwifi-ss#189]
填写一下以下几个问题
![qq20180116-152244](https://user-images.githubusercontent.com/6214084/34976345-2fab5934-fad1-11e7-97bd-bb2d513e2259.png)
系统版本 : HC5761 - 1.4.6.19458s    MAC : D4EE071111DC

**Comment by ykla** [comment]
一样

**Comment by qiwihui** [comment]
请尝试最新版
