### ISSUE TITLE
shadowsocks-libev 3.1.3静态编译文件 for Hiwifi

### ISSUE THREAD

**Issue by froer** [qiwihui/hiwifi-ss#190]
官方升级描述：Fix a bug in UDP relay.
https://github.com/shadowsocks/shadowsocks-libev/releases
[shadowsocks-libev_v3.1.3静态编译.zip](https://github.com/qiwihui/hiwifi-ss/files/1648603/shadowsocks-libev_v3.1.3.zip)

**Comment by qiwihui** [comment]
多谢支持！

**Comment by qiwihui** [comment]
已更新到最新
