### ISSUE TITLE
新版的样式有点不对。

### ISSUE THREAD

**Issue by lovage** [qiwihui/hiwifi-ss#197]
硬件是极路由Go HC5611 - 1.3.5.18462s

hiwifi-ss 版本：v1.0.6
样式有点不对，大佬抽时间更正下。 

https://i.imgur.com/dmUvqrR.png

**Comment by qiwihui** [comment]
这是新版hiwifi-ss没有适配老版hiwifi的问题，你可以选择一下其中一种解决方法：

1. 升级hiwifi到最新版 1.4.5

2. 不升级hiwifi：
ssh连进路由器，手动将/usr/lib/lua/luci/view/admin_web/prometheus/index.htm中的
/v2/style/admin_web/net.css 大概在14行左右
更换为
/v2/style/net.css

**Comment by lovage** [comment]
@qiwihui 
跪谢大佬，已经按照第二种方法修改完成。
