### ISSUE TITLE
新版本ss使用命令报错

### ISSUE THREAD

**Issue by Lstoryc** [qiwihui/hiwifi-ss#2]
wget: not an http or ftp url: https://raw.githubusercontent.com/qiwihui/hiwifi-ss/master/shadow.sh

**Comment by qiwihui** [comment]
@Lstoryc 这个wget下载https的url不太支持，已修改成使用curl了

```sh
cd /tmp && curl -k -o shadow.sh https://raw.githubusercontent.com/qiwihui/hiwifi-ss/master/shadow.sh && sh shadow.sh && rm shadow.sh

```

**Comment by qiwihui** [comment]
同时我修改了下载链接到我的服务器上，已测试可用。

**Comment by Lstoryc** [comment]
为何安装过程有报错信息的？

**Comment by qiwihui** [comment]
因为极路由后台的框架用的是luci， 有缓存机制，所以修改完lua代码后不会立即生效， 删除/tmp目录里面的luci相关缓存可以解决这个问题，故再代码里有判断是否有 `/tmp/luci-modulecache` 这一目录。这个暂时不影响功能。

**Comment by hkbobi** [comment]
我同样碰到了这个问题，luci-cache does not exist! 无法找到luci-cache,请确定是否是极路由环境，我的两个极路由2（HC5761）都是这个问题，并且在界面里，ss的开关没用，点导入配置也会报错，请问作者这个问题如何解决。

**Comment by hkbobi** [comment]
补充：这是我安装以后的图：http://i1.piimg.com/567571/6e3cea06eb77a67c.png  

点击 导入配置文件(json格式)的话会自动下载一个文件，文件名是cfg_import  里边的内容为：{ "msg": "请求的接口不存在.", "code": 560 }

**Comment by qiwihui** [comment]
@hkbobi 你试着重启路由器试试

**Comment by hkbobi** [comment]
@qiwihui  尝试了 我两台极路由2我都刷了 ，还有朋友一台都不可以，是不是极路由2不兼容？

**Comment by qiwihui** [comment]
@hkbobi 你的系统版本是哪一个？ 系统版本 : HC5761 - 1.0.7.13499s ？

**Comment by qiwihui** [comment]
@hkbobi 我自己用的也是极路由2(HC5761), 所以想知道你的极路由型号和系统版本。理论上1.0.7.13499s的版本都支持。
