### ISSUE TITLE
操作失败，请求的接口不存在？

### ISSUE THREAD

**Issue by TennyZhuang** [qiwihui/hiwifi-ss#20]
#### 问题描述

电脑直接连 ss 没问题，应该不是服务器的锅

#### 运行结果

![be7087c5-e8b5-43b2-b8d4-a876b2be3fec](https://cloud.githubusercontent.com/assets/9161438/18407813/0eef0c3e-774e-11e6-9867-44890f6da523.png)

**Comment by wangdaqiao** [comment]
安装后，重启路由器即可。

**Comment by qiwihui** [comment]
@wangdaqiao 😄是的
