### ISSUE TITLE
能不能把kcptun编译进去

### ISSUE THREAD

**Issue by mountainguan** [qiwihui/hiwifi-ss#21]
#### 问题描述

kcptun支持openwrt了，但是我又想用极路由的5G网络

**Comment by FengkuiChan** [comment]
这项目有进展吗？

**Comment by JohnsonCaii** [comment]
我成功在路由器上编译过kcptun，但这东西很吃CPU。
如果你路由器性能比较一般，建议不用这个。

接着我尝试了谷歌的BBR，因为是单边加速，所以在路由器上配置就不会有吃CPU的情况了。

**Comment by qiwihui** [comment]
会在下一个版加入kcptun

**Comment by mountainguan** [comment]
好的，谢谢

**Comment by PengDavin** [comment]
@qiwihui @mountainguan 
我发现 Kcptun 主程序太大了，旧极路由的 Flash (例如我的极路由2)完全放不下 Kcptun。因为在项目里面有编译后的kcptun，然后打包后在极路由上解压会说空间不足。
而且 @JohnsonCaii 说得很对，这东西很吃cpu，因为性能问题反而会影响网络的稳定性。

如果想要用kcptun，可以阅读一下https://stray.love/hiwifi/ji-lu-you-kcptun-jiao-cheng ，里面有教程以及插件可以下载。

建议在项目里删除kcptun相关的东西并且在ReadMe里面说明一下原因。如果有不同意见，欢迎讨论~
