### ISSUE TITLE
不需要把ss的包解压进去的，极路由官方源里就有包啊 opkg install shadowsocks-libev

### ISSUE THREAD

**Issue by xpalm** [qiwihui/hiwifi-ss#213]
填写一下以下几个问题
不需要把ss的包解压进去的，极路由官方源里就有包啊 opkg install shadowsocks-libev
1. 使用的 hiwifi-ss 版本

2. 问题产生过程

3. 你的期望

4. 运行结果

**Comment by qiwihui** [comment]
官方源里的shadowsocks-libev包太老，无法满足很多需求
