### ISSUE TITLE
连接错误

### ISSUE THREAD

**Issue by yeancai** [qiwihui/hiwifi-ss#217]
填写一下以下几个问题

1. 使用的 hiwifi-ss 版本
V1.0.6
2. 问题产生过程
开启提示连接错误
3. 你的期望
能用
4. 运行结果
连接错误

协议为 origin
混淆为 tls1.2_ticket_auth
电脑上可用。

**Comment by qiwihui** [comment]
这个是 ShadowsocksR 的混淆模式，现在不支持 ShadowsocksR ；
目前只支持了Shadowsocks及对应的obfs_simple混淆。
