### ISSUE TITLE
 HC5861 - 1.1.4.14678s 安装失败

### ISSUE THREAD

**Issue by kevin364** [qiwihui/hiwifi-ss#22]
#### 问题描述:
刚升级到1.1.4.14678s  重启后安装ss,
系统版本 : HC5861 - 1.1.4.14678s 安装失败

#### 运行结果
Building environment... 创建临时目录ing

Done! 成功创建临时目录!

Downloading files... 下载插件ing

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  243k  100  243k    0     0   3895      0  0:01:03  0:01:03 --:--:-- 43361
Done! 下载完成

Installing... 安装ing
备份系统文件........[完成]
Error,请备份并重命名/etc/config/ss-redir文件夹

**Comment by qiwihui** [comment]
你之前应该装过同样的插件吧。
可以重命名 `/etc/config/ss-redir` 并再次运行脚本即可。

**Comment by fujiwara-takumi** [comment]
我和题主碰到同样的问题，用winsck登陆进极路由并没有发现/etc/config/ss-redir文件夹
但是搜索到了2个s-redir文件。并不是文件夹的形式。

是提示的就是这个文件还是文件夹我现在有点迷糊。题主最后怎么解决的呢？

**Comment by qiwihui** [comment]
应该是文件，这个是因为之前装过ss，但是不知道这个和以前的有没有冲突，所以把之前的文件重命名就可以解决了。

**Comment by qiwihui** [comment]
referring to #38
