### ISSUE TITLE
希望增加一些类似ChinaDNS的功能 以及黑白名单功能

### ISSUE THREAD

**Issue by RhythmNz** [qiwihui/hiwifi-ss#220]
填写一下以下几个问题

1. 使用的 hiwifi-ss 版本
1.0.6
2. 问题产生过程
使用Vultr JP的SS 智能模式 Steam Warframe无法正常游玩
3. 你的期望
在智能模式[即非国内IP的情况下走SS]增加黑白名单 黑名单不走SS 白名单强制走SS
黑白名单希望同时支持域名/IP
这种情况出现的主要原因是因为通过SS来解析域名 域名服务器解析出了SS所在地的结果
Openwrt上有China-DNS 以114.114.114.114作为上游服务器 出现污染结果才进行SS+8.8.8.8解析
这种方式也能一定程度上缓解问题

**Comment by qiwihui** [comment]
自定义dns 2befe17ce4f261c920f137108077ed038dc5ec50
