### ISSUE TITLE
极二 目前最新版固件（1.4）SS运行显示【连接错误】

### ISSUE THREAD

**Issue by MMMMMMWM** [qiwihui/hiwifi-ss#226]
填写一下以下几个问题

1. 使用的 hiwifi-ss 版本
v1.0.7
2. 问题产生过程

HC5761 - 1.4.11.21001s
--
在该版固件 ，使用SS   
保存后点击运行，状态栏会显示 【连接错误】无法使用

3. 你的期望
希望能改善上述问题
4. 运行结果
无法使用

**Comment by qiwihui** [comment]
已修复了这个问题，v1.0.8，重新安装即可
