### ISSUE TITLE
v1.0.7 + 极路由1s 链接失败

### ISSUE THREAD

**Issue by eefolks** [qiwihui/hiwifi-ss#228]
1.新路由器自动安装 v1.0.7 ，ss配置后，连接失败；之前的路由器  相同配置，v1.0.6　works well.

2. 新路由器，手动安装v1.0.6可以正常work

3. 期望新版能在极路由１s work.

个人认为你的插件比hiwifi.easucks消耗资源少，官方查件回导致极路由1s巨卡．
hiwifi.easucks，很慢，且Google Home 不能用．其他服务没试．

**Comment by eefolks** [comment]
极路由1s FW :

HC5661A - 1.4.10.20837s

**Comment by stalxjason** [comment]
1.0.6版本怎么安装 我现在1.0.7版本也是一直提示链接错误 节点是正常的

**Comment by qiwihui** [comment]
已修复了这个问题，v1.0.8
