### ISSUE TITLE
极路由1s + v1.06 2018.08.02突然不能正常工作

### ISSUE THREAD

**Issue by eefolks** [qiwihui/hiwifi-ss#232]
昨天看到极路由老板也要被迫跑路了，下午翻墙就不能工作了。这是巧合么。～～～。　

1.通过路由器访问国内网址没问题。但被墙的网址不能访问。
2.hiwifi-ss 配置页面显示红色的不能正常链接。
3.重新安装v1.0.8 ，和step2相同现象。
4.恢复出厂设置安装推荐的 Paull/hiwifi.easucks　，页面看起来链接正常，但实际不能成功访问被墙网址
5. Paull/hiwifi.easucks/hiwifi-ss，这两种方案以前都试过，OK,从昨天开始突然都失效了。这两个工程有什么相同的依赖？？

**Comment by eefolks** [comment]
发现一个有趣现象：
1．关闭安全上网，可以上github
2．打开安全上网(红色　连接错误)(智能模式)，github访问失败
3．打开安全上网(红色　连接错误)(全局模式)，国内/国外　都访问失败

**Comment by eefolks** [comment]
VTS重启，好了。可能和欠费有关系。

**Comment by q629988171** [comment]
可惜，极路由的1S是性价比高的一款路由器产品，极路由可直接USB供电，功耗低（方便在停电的时候移动电源提供可持续网络），一个开放的路由器系统可随意安装第三方软件（提供更丰富功能），最后建议大家将好用的插件下载存档，以免极路由倒闭停服。
