### ISSUE TITLE
HC5661A - 1.2.2.15132s 安装后无法打开SS界面

### ISSUE THREAD

**Issue by chuan0932** [qiwihui/hiwifi-ss#24]
极路由最新固件貌似又更改了API接口 刷完SS之后互联网界面一直在读取 进不了ss子菜单 求更新

**Comment by qiwihui** [comment]
我需要具体查一下这个问题

**Comment by qiwihui** [comment]
referring to #38

**Comment by moc375** [comment]
看到这个问题已经关闭了，想问一下出解决方法了吗？我也是遇到题主同样的问题

**Comment by hemoely** [comment]
HC5661A - 1.2.5.15805s 一直在互联网那转圈圈怎么搞！！！
