### ISSUE TITLE
【推荐】稳定快速的机场节点、最新科学上网方法

### ISSUE THREAD

**Issue by hardwellhard** [qiwihui/hiwifi-ss#262]
最新科学上网方法：[科学上网方法](https://github.com/hardwellhard/FreePAC)

如果不想搭建，可以直接使用稳定机场或节点：
[稳定快速机场节点](https://github.com/hardwellhard/FreePAC/blob/master/VPN%20SSR.md)

**Comment by whp520** [comment]
在哪
