### ISSUE TITLE
安装直接ERROR

### ISSUE THREAD

**Issue by EasonZeng** [qiwihui/hiwifi-ss#3]
极路由3  系统版本 : HC5861 - 1.0.7.13499s

root@Hiwifi:~# cd /tmp && curl -k -o shadow.sh https://raw.githubusercontent.com
/qiwihui/hiwifi-ss/master/shadow.sh && sh shadow.sh && rm shadow.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2103  100  2103    0     0   1181      0  0:00:01  0:00:01 --:--:--  1186

/*教程请参考:极路由Shadowsocks家庭无痛翻墙实践*/
https://luolei.org/hiwifi-shadowsocks/
by @foru17

那一天,
人类终于回想起了,
曾经一度被他们所支配的恐怖,
还有被囚禁于鸟笼中的那份屈辱.

進撃の巨人 諫山創

Building environment... 创建临时目录ing

Done! 成功创建临时目录!

Downloading files... 下载插件ing

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  192k  100  192k    0     0   9890      0  0:00:19  0:00:19 --:--:-- 24816
Done! 下载完成

Installing... 安装ing
Error
root@Hiwifi:/tmp# ../
-ash: ../: Permission denied
root@Hiwifi:/tmp# cd
root@Hiwifi:~# cd /tmp && curl -k -o shadow.sh https://raw.githubusercontent.com
/qiwihui/hiwifi-ss/master/shadow.sh && sh shadow.sh && rm shadow.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2103  100  2103    0     0   1217      0  0:00:01  0:00:01 --:--:--  1221

/*教程请参考:极路由Shadowsocks家庭无痛翻墙实践*/
https://luolei.org/hiwifi-shadowsocks/
by @foru17

那一天,
人类终于回想起了,
曾经一度被他们所支配的恐怖,
还有被囚禁于鸟笼中的那份屈辱.

進撃の巨人 諫山創

Building environment... 创建临时目录ing

Done! 成功创建临时目录!

Downloading files... 下载插件ing

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  192k  100  192k    0     0  33388      0  0:00:05  0:00:05 --:--:-- 39990
Done! 下载完成

Installing... 安装ing
Error

**Comment by qiwihui** [comment]
@EasonZeng 你是不是第一次安装这个插件？

**Comment by qiwihui** [comment]
@EasonZeng 这个应该是脚本中对存在文件的判断问题，这个可能和这个版本之前需要支持其他版本做的兼容。我会提交一个修复。

**Comment by EasonZeng** [comment]
@qiwihui 好的谢谢

**Comment by qiwihui** [comment]
@EasonZeng 你之前有装过ss的插件或者有 `/etc/config/ss-redir` 这个文件么？

**Comment by EasonZeng** [comment]
@qiwihui 之前装过SS插件，有这个文件夹！

**Comment by EasonZeng** [comment]
@qiwihui 
root@Hiwifi:/etc# cd config/
root@Hiwifi:/etc/config# ls
ap_binding                 inetchk                    prostat                    switch_status
bridge                     luci                       qos                        system
device_model               mentohust                  radvd                      tester
device_rpt_binding         mobile                     redsocks                   tnetwork
devicetimer                mobile_backup_user_config  remote_script_enable       twx_3g
dhcp                       mtkswitch                  safeboot                   upnpd
dnscrypt-proxy             network                    samba                      watchdog
dropbear                   network-conf               shadowsocks                wifi_sleep
firewall                   network_tester             smart_device_place         wireless
gatekeeper                 notice                     speeddtest                 wireless_mac_save
guestwifi                  notice_0_9008              speedtest                  wireless_macfilter_backup
guide                      openapi                    sqos                       x3c8021x
hiwifi                     openvpn                    ss-redir
inet_chk                   phylong                    statistics

**Comment by qiwihui** [comment]
@EasonZeng 如果ss插件没有用了就删了那个文件夹和那个ss-redir文件吧，这样就可以过了

**Comment by EasonZeng** [comment]
@qiwihui 2个指的是`ss-redir`和`shadowsocks`？

**Comment by qiwihui** [comment]
@EasonZeng 对， `/usr/lib/lua/luci/view/admin_web/plugin/shadowsocks.htm`和 `/etc/config/ss-redir`

**Comment by EasonZeng** [comment]
@qiwihui 纳尼。我是修改的`/etc/config/ss-redir`和`/etc/config/shadowsocks`但是已经安装成功，另外有个问题ss中的高级设置页面是这样
`
Status: 500 Internal Server Error Failed to execute template dispatcher target for entry '/api/geewan/ss_adv'. The called action terminated with an exception: Failed to execute template 'admin_web/network/ss_adv'. A runtime error occured: Failed to load template 'admin_web/menu/adv_menu'. Error while parsing template '/usr/lib/lua/luci/view/admin_web/menu/adv_menu.htm'. A syntax error occured near 'No such file or directory'. stack traceback: [C]: in function 'assert' ?: in function 'dispatch' ?: in function`

**Comment by EasonZeng** [comment]
@qiwihui 
![qq 20160806005130](https://cloud.githubusercontent.com/assets/4544918/17444053/837a7c40-5b70-11e6-984c-f9efd7efd76e.png)

**Comment by qiwihui** [comment]
@EasonZeng "导入配置文件(json格式)" 和 "高级设置" 这两个功能正在修复中， 请等到更新

**Comment by EasonZeng** [comment]
@qiwihui THX！静候佳音

**Comment by qiwihui** [comment]
@EasonZeng ss高级设置功能已修复

**Comment by qiwihui** [comment]
"导入配置文件(json格式)"正在修复，会在稍后几天提交。
