### ISSUE TITLE
能否提供自定DNS的功能？

### ISSUE THREAD

**Issue by neoAimeow** [qiwihui/hiwifi-ss#30]
现在列表里的DNS服务并不是我想要的，这里能提供自定义的功能么？

**Comment by qiwihui** [comment]
hmmm，貌似还不能

**Comment by neoAimeow** [comment]
嗯，我试用了一段时间你提供的ss...并且自己有做一些改动尝试。。发现其实有时候不设置DNS会更稳定。。。不然可能会冲突。我在页面里把dns移除掉后，验证了几天，目前没出现过问题。

**Comment by silverHugh** [comment]
我有这样一个问题：
使用gee路由上的shadowsocks访问google.com会给我自动重定向到google.com.hk，
而用电脑上的shadowsocks客户端则不会。
我怀疑是DNS的原因？还是其他怎么一回事？

**Comment by hugoecho** [comment]
同遇到访问google.com自动重定向到google.com.hk，求解决办法

**Comment by qiwihui** [comment]
已增加自定义DNS
