### ISSUE TITLE
服务器地址不支持域名必须用ip？

### ISSUE THREAD

**Issue by txdywy** [qiwihui/hiwifi-ss#32]
#### 问题描述
尝试使用微林中继加速或其他第三方提供的ss，会提供一个域名而非ip。

#### 运行结果
使用域名不能运行。只能使用ip

**Comment by qiwihui** [comment]
可以使用域名。我自己的极路由就是用了域名，你再试试看

**Comment by txdywy** [comment]
我这的现象是设成域名保存后就不能运行，然后试着把域名解析的ip填上就好了。。。

系统版本 : HC5661A - 1.1.4.14678s

**Comment by qiwihui** [comment]
能截个图看看么

**Comment by txdywy** [comment]
昨天好像又试了一个不确定是不是运行了...

晚上回家再确认一下!

**Comment by txdywy** [comment]
后来发现有问题的多保存一次就运行了
