### ISSUE TITLE
我的是极路由1 ROM：1.1.4.14678s 安装完就是找不到那个菜单

### ISSUE THREAD

**Issue by jiangjijiji** [qiwihui/hiwifi-ss#34]
#### 问题描述

安装完会有提示，luci-cache does not exist question，重起过就是还是找不到那个菜单，奇怪了。求助。感谢。

**Comment by qiwihui** [comment]
@jiangjijiji 能提供完整报错提示吗？

**Comment by jiangjijiji** [comment]
作者你好，感谢回复。
就是和#16 这里的一个情况一样：
“luci-cache does not exist! 无法找到luci-cache,请确定是否是极路由环境。”

也是有提示说成功了安装，我重启后界面里没有这个SS菜单。我也可以回去再看看。

**Comment by jiangjijiji** [comment]
我的全部情况：

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2578  100  2578    0     0   1020      0  0:00:02  0:00:02 --:--:--  1020

/*教程请参考:极路由Shadowsocks家庭无痛翻墙实践*/
https://luolei.org/hiwifi-shadowsocks/
by @foru17


那一天,
人类终于回想起了,
曾经一度被他们所支配的恐怖,
还有被囚禁于鸟笼中的那份屈辱.

進撃の巨人 諫山創

Building environment... 创建临时目录ing

Done! 成功创建临时目录!

Downloading files... 下载插件ing

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  243k  100  243k    0     0   116k      0  0:00:02  0:00:02 --:--:--  116k
Done! 下载完成

Installing... 安装ing
-n 备份系统文件....
cp: /usr/lib/lua/luci/view/admin_web/network/index.htm: No such file or directory
-e ....[\e[32m完成\e[37m]
x etc/: Could not remove symlink etc
x etc/config/: Cannot extract through symlink etc
x etc/firewall.d/: Cannot extract through symlink etc
x etc/gw-redsocks/: Cannot extract through symlink etc
x etc/gw-redsocks.conf: Cannot extract through symlink etc
x etc/gw-shadowsocks/: Cannot extract through symlink etc
x etc/init.d/: Cannot extract through symlink etc
x etc/rc.d/: Cannot extract through symlink etc
x etc/ss/: Cannot extract through symlink etc
x etc/ss/ss-init: Cannot extract through symlink etc
x etc/ss/ss-lib: Cannot extract through symlink etc
x etc/rc.d/S80gw-shadowsocks: Cannot extract through symlink etc
x etc/init.d/dnscrypt-proxy: Cannot extract through symlink etc
x etc/init.d/gw-redsocks: Cannot extract through symlink etc
x etc/init.d/gw-shadowsocks: Cannot extract through symlink etc
x etc/gw-shadowsocks/gw-shadowsocks.dnslist: Cannot extract through symlink etc
x etc/gw-redsocks/gw-shadowsocks/: Cannot extract through symlink etc
x etc/gw-redsocks/gw-shadowsocks/gw-shadowsocks.dnslist: Cannot extract through symlink etc
x etc/firewall.d/10-shadowsocks: Cannot extract through symlink etc
x etc/config/dnscrypt-proxy: Cannot extract through symlink etc
x etc/config/shadowsocks: Cannot extract through symlink etc
x lib/: Can't create 'lib'
x lib/gw-shadowsocks.sh: Failed to create dir 'lib'Can't create 'lib/gw-shadowsocks.sh'
x lib/ss-test.lua: Failed to create dir 'lib'Can't create 'lib/ss-test.lua'
x usr/: Can't update time for usr
x usr/bin/: Can't update time for usr/bin
x usr/lib/: Can't update time for usr/lib
x usr/sbin/: Can't update time for usr/sbin
x usr/sbin/dns2socks: Can't create 'usr/sbin/dns2socks'
x usr/sbin/ss-redir: Can't create 'usr/sbin/ss-redir'
x usr/lib/lua/: Can't create 'usr/lib/lua'
x usr/lib/opkg/: Can't create 'usr/lib/opkg'
x usr/lib/opkg/info/: Failed to create dir 'usr/lib/opkg'Can't create 'usr/lib/opkg/info'
x usr/lib/opkg/info/geewan-ss.control: Failed to create dir 'usr/lib/opkg'Can't create 'usr/lib/opkg/info/geewan-ss.control'
x usr/lib/opkg/info/geewan-ss.list: Failed to create dir 'usr/lib/opkg'Can't create 'usr/lib/opkg/info/geewan-ss.list'
x usr/lib/lua/geewan.lua: Failed to create dir 'usr/lib/lua'Can't create 'usr/lib/lua/geewan.lua'
x usr/lib/lua/luci/: Failed to create dir 'usr/lib/lua'Can't create 'usr/lib/lua/luci'
x usr/lib/lua/luci/controller/: Failed to create dir 'usr/lib/lua'Can't create 'usr/lib/lua/luci/controller'
x usr/lib/lua/luci/view/: Failed to create dir 'usr/lib/lua'Can't create 'usr/lib/lua/luci/view'
x usr/lib/lua/luci/view/admin_web/: Failed to create dir 'usr/lib/lua'Can't create 'usr/lib/lua/luci/view/admin_web'
x usr/lib/lua/luci/view/admin_web/network/: Failed to create dir 'usr/lib/lua'Can't create 'usr/lib/lua/luci/view/admin_web/network'
x usr/lib/lua/luci/view/admin_web/network/cfg_import.htm: Failed to create dir 'usr/lib/lua'Can't create 'usr/lib/lua/luci/view/admin_web/network/cfg_import.htm'
x usr/lib/lua/luci/view/admin_web/network/index.htm: Failed to create dir 'usr/lib/lua'Can't create 'usr/lib/lua/luci/view/admin_web/network/index.htm'
x usr/lib/lua/luci/view/admin_web/network/shadowsocks.htm: Failed to create dir 'usr/lib/lua'Can't create 'usr/lib/lua/luci/view/admin_web/network/shadowsocks.htm'
x usr/lib/lua/luci/view/admin_web/network/ss_adv.htm: Failed to create dir 'usr/lib/lua'Can't create 'usr/lib/lua/luci/view/admin_web/network/ss_adv.htm'
x usr/lib/lua/luci/controller/admin_web/: Failed to create dir 'usr/lib/lua'Can't create 'usr/lib/lua/luci/controller/admin_web'
x usr/lib/lua/luci/controller/api/: Failed to create dir 'usr/lib/lua'Can't create 'usr/lib/lua/luci/controller/api'
x usr/lib/lua/luci/controller/api/geewan.lua: Failed to create dir 'usr/lib/lua'Can't create 'usr/lib/lua/luci/controller/api/geewan.lua'
x usr/lib/lua/luci/controller/admin_web/shadowsocks.lua: Failed to create dir 'usr/lib/lua'Can't create 'usr/lib/lua/luci/controller/admin_web/shadowsocks.lua'
x usr/bin/gw_redsocks: Can't create 'usr/bin/gw_redsocks'
x usr/bin/ss-local: Can't create 'usr/bin/ss-local'
x usr/bin/ss-redir: Can't create 'usr/bin/ss-redir'
x usr/bin/ss-tunnel: Can't create 'usr/bin/ss-tunnel'
tar: Error exit delayed from previous errors.
Done! 插件安装成功!

adding uninstall information... 准备删除临时文件...

shadow.sh: line 51: /usr/lib/opkg/status: No such file or directory
shadow.sh: line 52: /usr/lib/opkg/status: No such file or directory
shadow.sh: line 53: /usr/lib/opkg/status: No such file or directory
shadow.sh: line 54: /usr/lib/opkg/status: No such file or directory
shadow.sh: line 55: /usr/lib/opkg/status: No such file or directory
shadow.sh: line 56: /usr/lib/opkg/status: No such file or directory
shadow.sh: line 57: /usr/lib/opkg/status: No such file or directory
shadow.sh: line 58: /usr/lib/opkg/status: No such file or directory
shadow.sh: line 59: /usr/lib/opkg/status: No such file or directory
cleanning temporary files... 清理临时文件ing

luci-cache does not exist! 无法找到luci-cache,请确定是否是极路由环境

the whole installation Success! 插件成功安装!
1987年9月14日21时07分
中国第一封电子邮件
从北京发往德国
越过长城，走向世界
Done! Hello World! 一切就绪,你好世界!

**Comment by qiwihui** [comment]
你需要ssh进入路由器后台然后运行命令，而不是在你的电脑上运行命令。

**Comment by jiangjijiji** [comment]
我又去参看了一遍教程，都已经安装好了，也能看到操作界面。
但有伴随出现了一个新的问题：就是我都配置好了可是无法运营，路由器也重启过了，由于不知道超时时间怎么填写，我就写了100，DNS是谷歌的。

我非常确认这个ss是正确的，信息也对，因为我自己平时用电脑和手机上用的shawodsocks就是这个，请告知如何解决这个，就最后一步了，非常感谢作者！

**Comment by astaxie** [comment]
配置了正确的ss，google的dsn，我也遇到相同的问题，配置完之后状态是未运行，请问哪里可以检查？

系统版本 : 1.1.4.14678s

**Comment by qiwihui** [comment]
点击保存

**Comment by qiwihui** [comment]
@jiangjijiji @astaxie

**Comment by astaxie** [comment]
@qiwihui 点击保存了，而且已经重启好多遍了。状态始终显示未运行

**Comment by qiwihui** [comment]
@astaxie will check tomorrow

**Comment by jiangjijiji** [comment]
我后来买了一个极路由3，来配置了，保存后能运行。而且效果很不错。
虽然极1没用上，但也是非常感谢了。

**Comment by astaxie** [comment]
看来极1不支持

**Comment by qiwihui** [comment]
referring to #38

**Comment by createyoung** [comment]
@jiangjijiji 我的情况和你一模一样，不知道你后来在极1上成功了没有？

**Comment by panw3i** [comment]
有结果吗？我的情况和你一样的

**Comment by iamcho** [comment]
我也一直是菊花转,后来退出ssh后重连,用的
cd /tmp && curl -k -o shadow.sh https://raw.githubusercontent.com/cllu/hiwifi-ss/hiwifi-v1.2.5/shadow.sh && sh shadow.sh && rm shadow.sh
好了,成功了,希望对你们有帮助
