### ISSUE TITLE
SS 用的是什么过滤规则？GFWList还是大陆白名单？

### ISSUE THREAD

**Issue by reaCodes** [qiwihui/hiwifi-ss#35]
#### 问题描述
-----------------------------
我访问几个国外查看IP的网站，都显示我的代理服务器IP，那么我就怀疑是不是这个版本的SS和官方版本一样，采用的是大陆白名单规则？
如果是大陆白名单，我该怎么使用GFWList？如果是GFWList，我又该怎么去更新它？

**Comment by qiwihui** [comment]
ss使用的是gfwlist，符合规则的域名或者ip走代理，其他正常访问。

**Comment by qiwihui** [comment]
更新gfwlist参考 #4

**Comment by reaCodes** [comment]
可是我测试的结果是，好多没有被墙的网站都使用了代理，比如www.infobyip.com 
https://www.whatismyip.com/my-ip-information
https://ipinfo.io/
这些网站检测到我访问的来源都是那个代理服务器的IP
不知道什么原因！

**Comment by qiwihui** [comment]
hmmm, 我查看一下

**Comment by qiwihui** [comment]
我之前的解释错了。
目前ss用的是白名单模式。

**Comment by reaCodes** [comment]
Okey，那能不能改成使用GFWList？

**Comment by qiwihui** [comment]
如果你想换成黑名单模式，你可以这么做：
将 `/etc/init.d/gw-redsocks` 36~40行替换为

```
iptables -t nat -A $appname -p tcp -m set --match-set gfwlist dst -j DNAT --to-destination $lan_ip:$rs_port_tcp
iptables -t nat -A $appname -p tcp -m salist --salist gfwlist --match-dip -j DNAT --to-destination $lan_ip:$rs_port_tcp
```

**Comment by reaCodes** [comment]
@qiwihui 规则什么的不用动吗？GFWList如何更新？

**Comment by qiwihui** [comment]
目前gfw规则的时间是 2016-08-07，手动更新请使用项目 [gfwlist2dnsmasq](https://github.com/cokebar/gfwlist2dnsmasq) 里的脚本更新，生成的结果手动改成本项目需要的格式就可以了。

**Comment by reaCodes** [comment]
@qiwihui 按照你说的改了，插件能启动，但是一直提示无法加速😅

**Comment by qiwihui** [comment]
one question, one issue. thx.

**Comment by qiwihui** [comment]
referring to #37

**Comment by pbbqdd** [comment]
怀疑/etc/salist 下的config 中没有gfwlist列表导致不能使用黑名单模式。salist --salist gfwlist 里没有gfwlist列表

**Comment by pbbqdd** [comment]
salist 没有gwf列表

**Comment by pbbqdd** [comment]
salist 这个列表里没有gfwlist ipset可以用

**Comment by dawnnao** [comment]
@qiwihui hiwifi-ss 目前用的是大陆白名单模式，那我该如何手动添加个别域名进去呢？

**Comment by hybtw** [comment]
iptables -t nat -A $appname -p tcp -m set --match-set gfwlist dst -j DNAT --to-destination $lan_ip:$rs_port_tcp
iptables -t nat -A $appname -p tcp -m salist --salist gfwlist --match-dip -j DNAT --to-destination $lan_ip:$rs_port_tcp
ipset和salist都没有gfwlist吧？

**Comment by wl1244hotmai** [comment]
这两行sh是不是有问题

**Comment by vicode0768** [comment]
@qiwihui @q629988171 gfwlist里面的格式是需要什么样的？

**Comment by q629988171** [comment]
@vicode0768 gfwlist 格式是 "server=/ctao.org/127.0.0.1#53535"

**Comment by pbbqdd** [comment]
恩，我有点明白了。需要把改好的gfwlist添加到/etc/salist里再启用以上命令是这样吧。

**Comment by w0o0** [comment]
https://github.com/Paull/hiwifi.easucks

搜索到这个项目，目前支持GFWList，同时支持“黑白名单”（与这里的概念有点不一样），也支持mac地址过滤，极2A（HC5761A - 1.3.5.18462s）亲测有效。
