### ISSUE TITLE
白名单模式如何进行私人订制？

### ISSUE THREAD

**Issue by JoshYEn** [qiwihui/hiwifi-ss#39]
#### 问题描述
请问白名单模式如何进行**订制**？

**Comment by qiwihui** [comment]
根据 /etc/init.d/gw-redsocks 第 [37](https://github.com/qiwihui/hiwifi-ss/blob/master/etc/init.d/gw-redsocks#L37) 行的描述，项目中使用的白名单来自极路由自带的IP列表。这个规则在 `/proc/nf_salist/` 下

```sh
root@Hiwifi:~# ls /proc/nf_salist/
cernet   china    cmcc     control  hiwifi   local    telecom  unicom
```

所以修改 `china` 这个里面的配置应该就可以了

**Comment by qiwihui** [comment]
白名单模式和gfwlist模式不太一样，我想你指的是白名单模式。

**Comment by shipenzildk** [comment]
> qiwihui commented 11 hours ago
> 白名单模式和gfwlist模式不太一样，我想你指的是白名单模式。
我的 /proc/nf_salist/ 下几个文件都是 0KB 空白的,如果不想让teamviewer走代理,应该怎么做?

**Comment by JoshYEn** [comment]
您好，我的问题是这样的。
我对Proxy Config的理解是：
对于选择智能模式，这时使用的是GFWlist；对于全局模式，使用的是白名单，仅跳过了localhost。
请问是这样吗？

如果是的话，分别如何怎样进行配置呢？
非常感谢！

**Comment by liaol** [comment]
@shipenzildk cat能看到

**Comment by fengertao** [comment]
描述一下问题：
/proc/nf_salist/这个目录不是普通目录，似乎里面的文件都是进程？
(1) cd /proc/nf_salist/ && ls -l
可以看见每个文件的长度都是0
(2)cat china
可以看见白名单的ip range显示在屏幕上
(3)vi china
编辑的是一个空文件。随便加几个IP地址，存盘。然后cat china，文件内容还是vi前的内容。

请问怎么编辑白名单。

**Comment by dawnnao** [comment]
和 @fengertao 情况一样样，求教！

**Comment by ikkyu0319** [comment]
情况和@fengertao @dawnnao 一样，求助~

**Comment by q629988171** [comment]
@ikkyu0319 @dawnnao @liaol @shipenzildk @JoshYEn 

/proc 文件系统是一个伪文件系统， 它只存在内存当中。

添加白名单：echo 209.58.128.92 >> /proc/nf_salist/china

验证：cat /proc/nf_salist/china | grep 209.58.128.92

永久写入：vi /etc/salist/china.conf

**Comment by qiwihui** [comment]
已经加入了白名单功能
