### ISSUE TITLE
希望更新SS2.5.6版本,添加一次性验证等..

### ISSUE THREAD

**Issue by dNEryno** [qiwihui/hiwifi-ss#42]
#### 问题描述
我的路由器版本 HC5661A - 1.1.4.14678s ..可以安装,应该也是可以运行的..我的要一次性验证还有chacha20-ietf..所以没运行成功..
#### 运行结果
再接再厉吧..

**Comment by Umi97** [comment]
HC5661A - 1.1.4.14678s,可以安装，aes-256-cfb方式可用，但是cahcha20就用不起来~

**Comment by qiwihui** [comment]
chacha20需要配置服务器端

**Comment by qiwihui** [comment]
chacha20已支持

**Comment by dNEryno** [comment]
额 路由器已经卖了
