### ISSUE TITLE
 极路由4 HC5962 - 固件1.2.5.15805s 刷完SS互联网页面一直在加载中无法打开

### ISSUE THREAD

**Issue by wzs1990** [qiwihui/hiwifi-ss#43]
#### 问题描述
 极路由4 HC5962 - 固件1.2.5.15805s 刷完SS互联网页面一直在加载中无法打开
#### 运行结果

一直在加载中无法打开

**Comment by szjjcm** [comment]
1.2.5.15805s 官方更新了api

建议降级到1.1.4.14678s 再刷ss插件。

目前，正式版本是1.1.4.14678s 
预发布版是1.2.5.15805s
在云平台上可以设置的。

如果是极先锋之类的。
可以ssh上去

cd /tmp
wget http://ur.ikcd.net/HC5962-sysupgrade-20160901-915be9de.bin
sysupgrade HC5962-sysupgrade-20160901-915be9de.bin

来降级。



wget 的固件地址，请对应 http://www.hiwifi.com/rom  ，找到对应的路由器固件

**Comment by wangzhenyu1260** [comment]
请见 #38

**Comment by xiongpeng78** [comment]
其他极路由器是同理一样操作吗？

**Comment by wzs1990** [comment]
固件1.2.5.15805s 刷SS

cd /tmp && curl -k -o shadow.sh https://raw.githubusercontent.com/cllu/hiwifi-ss/hiwifi-v1.2.5/shadow.sh && sh shadow.sh && rm shadow.sh

**Comment by MJ5201314** [comment]
终于找到个极路由4能用的了
