### ISSUE TITLE
极路由2 HC5761 - 1.2.5.15805s   版本，刷完这个插件互联网配置页面打不开

### ISSUE THREAD

**Issue by sikros** [qiwihui/hiwifi-ss#44]
#### 问题描述
极路由2 HC5761 - 1.2.5.15805s   版本，刷完这个插件互联网配置页面打不开
#### 运行结果

一直卡在加载页面

**Comment by szjjcm** [comment]
1.2.5.15805s 官方更新了api  

建议降级到1.1.4.14678s 再刷ss插件。


目前，正式版本是1.1.4.14678s 
   预发布版是1.2.5.15805s
在云平台上可以设置的。

如果是极先锋之类的。
可以ssh上去

cd /tmp
wget http://ur.ikcd.net/HC5761-sysupgrade-20160901-e321e7be.bin
sysupgrade HC5761-sysupgrade-20160901-e321e7be.bin

来降级。

**Comment by wangzhenyu1260** [comment]
请见 #38

**Comment by Minami-Kotori** [comment]
image name len error(HC5861B HC5761)
Image check 'platform_check_image' failed.
Unlocking hw_panic ...
Writing from /tmp/sysupgrade_log to hw_panic ...

**Comment by qiwihui** [comment]
请看新的readme或者见issue #38
