### ISSUE TITLE
极路由3 HC5861 - 1.2.5.15805s 版本，刷完这个插件互联网配置页面打不开

### ISSUE THREAD

**Issue by skyforest0591** [qiwihui/hiwifi-ss#46]
#### 问题描述
极路由3 HC5861 - 1.2.5.15805s 版本，刷完这个插件互联网配置页面打不开

#### 运行结果
一直卡在加载页面

**Comment by LaoYaos** [comment]
HC5861 - 1.2.5.15805s  遇到同样的问题

**Comment by skyforest0591** [comment]
1.2.5.15805s 官方更新了api

建议降级到1.1.4.14678s 再刷ss插件。

老版本是1.1.4.14678s
新版本是1.2.5.15805s
解决办法：
cd /tmp
wget http://ur.ikcd.net/HC5861-sysupgrade-20160901-0953a61e.bin
sysupgrade HC5861-sysupgrade-20160901-0953a61e.bin

来降级。
