### ISSUE TITLE
极1S手贱更新了系统（现：HC5661A-1.2.5.15805s） 互联网界面一直加载中

### ISSUE THREAD

**Issue by chuangyige** [qiwihui/hiwifi-ss#48]
#### 问题描述
如图：

![image 2016 12 02](https://cloud.githubusercontent.com/assets/4560683/20816622/406cb3aa-b85e-11e6-9191-e4c98b3ecd3f.png)

更新前正常。

**Comment by wangzhenyu1260** [comment]
一样问题

**Comment by wangzhenyu1260** [comment]
请见 #38

**Comment by chuangyige** [comment]
谢谢，已解决。

**Comment by hemoely** [comment]
@chuangyige  怎么解决的？求帮助

**Comment by doublemarkpro** [comment]
@hemoely 请参考 #38，刷入新的脚本
