### ISSUE TITLE
安装后报错 "luci-cache does not exist! 无法找到luci-cache,请确定是否是极路由环境"，但可以使用

### ISSUE THREAD

**Issue by asicsyao** [qiwihui/hiwifi-ss#5]
按照最新的一键命令，
cd /tmp && curl -k -o shadow.sh https://raw.githubusercontent.com/qiwihui/hiwifi-ss/master/shadow.sh && sh shadow.sh && rm shadow.sh
可还是报错：
 luci-cache does not exist! 无法找到luci-cache,请确定是否是极路由环境

**Comment by vnvvnv** [comment]
额 我也出现了这个提示 但是还是安装上了。

**Comment by asicsyao** [comment]
你如何验证你安装上了？

**Comment by vnvvnv** [comment]
- - 我已经用上了，不过比知道为什么有的网站打开的不是很顺畅，小飞机却可以。比如ins
![qq 20160807134804](https://cloud.githubusercontent.com/assets/20878096/17460751/9ab610aa-5ca5-11e6-88fa-fd1f5188d5ed.png)

**Comment by asicsyao** [comment]
我在后台管理界面还是找不到SS的图标入口啊

**Comment by asicsyao** [comment]
不对，我不想CLOSE

**Comment by vnvvnv** [comment]
装好了 要重启路由器的。
还有就是SS界面在互联网这个目录里面。。。

**Comment by vnvvnv** [comment]
你来我的群里扯 在这里麻烦额。。。邮件叮咚个不停！：
来来来121261010

**Comment by qiwihui** [comment]
@asicsyao `luci-cache does not exist! 无法找到luci-cache,请确定是否是极路由环境`这个报错可以无视，不影响功能

**Comment by asicsyao** [comment]
我重启路由后也找到可以了。

**Comment by asicsyao** [comment]
实在不好意思，打搅你午睡了，呵呵

**Comment by qiwihui** [comment]
@vnvvnv 这个问题是因为我昨天更新的gfwlist不全，导致有几个网站不能使用，我已经提交了一个patch修复这个问题了，你可以再次安装就，然后关闭开启ss就可以了

**Comment by vnvvnv** [comment]
- -搞了半天你没重启路由器 装了第三方插件重启路由器是常识呀！！亲~  我现在纳闷为什么我打不开谷歌搜索。。。。

**Comment by qiwihui** [comment]
@asicsyao 没关系，我要对这个项目负责嘛 :)
ps. 本人不午睡的，哈哈

**Comment by asicsyao** [comment]
赞！建议可以添加多个SS服务器并切换

**Comment by atom123123** [comment]
thx, but after reboot the hiwifi, the "Internet" tab is always loading...
