### ISSUE TITLE
打不开google中国开发者网站

### ISSUE THREAD

**Issue by sinkcup** [qiwihui/hiwifi-ss#50]
#### 问题描述
用了ss，打不开 developers.google.cn，而google.com没问题，用手机流量可以打开developers.google.cn。
官方新闻：2016年12月8日 Google开发者大会在北京召开，Google 全球开发者产品总监本·盖世（Ben Galbraith）在主题演讲中分享Google给中国开发者们专门订制的开发工具和平台：developers.google.cn

#### 运行结果

无法访问此网站
developers.google.cn 的响应时间过长。

**Comment by qiwihui** [comment]
developers.google.cn 可以访问，请使用智能模式。
