### ISSUE TITLE
希望增加黑名单模式！

### ISSUE THREAD

**Issue by Myoko** [qiwihui/hiwifi-ss#52]
#### 问题描述
希望增加黑名单模式！目前白名单模式很多国内的网站没有被墙的都走了SS代理流量！
希望下次更新能增加黑名单模式这样可以定义被墙的走SS流量这样就好了

**Comment by reaCodes** [comment]
非常希望增加一个黑名单的选择，只有白名单和全局，太不方便了😁

**Comment by ww1516123** [comment]
同求，增加设备或者ip黑名单

**Comment by hybtw** [comment]
etc/gw-shadowsocks目录下有个shadowsocks.dnslist文件，内容就是gfwlist的域名吧，这个文件怎么利用？

**Comment by qiwihui** [comment]
#37

**Comment by qiwihui** [comment]
已经加入黑名单模式
