### ISSUE TITLE
系统版本 : HC5761 - 1.1.4.14678s 

### ISSUE THREAD

**Issue by panw3i** [qiwihui/hiwifi-ss#54]
#### 问题描述
系统版本 : HC5761 - 1.1.4.14678s  不支持
#### 运行结果
多次重启路由器，界面没有选项

**Comment by cy-xu** [comment]
手贱升级了 HC5761 - 1.2.5.15805s
现在安装脚本结束后后台菜单一直转圈没有选项

**Comment by qiwihui** [comment]
请告知运行后的输出

**Comment by qiwihui** [comment]
或者升级到新版本安装新的插件

**Comment by qiwihui** [comment]
close as no further information.
