### ISSUE TITLE
就想问问大家是否能安装 VPN服务器插件

### ISSUE THREAD

**Issue by q629988171** [qiwihui/hiwifi-ss#59]
#### 问题描述
型号版本： HC5962 - 1.2.5.15805s （极4）
未root 的极3可以顺利安装，这个 root 后的极4 怎么也安装不上，反复安装，重启也不行。
#### 运行结果
失败提示：No offline package selective for this architecture.

**Comment by q629988171** [comment]
恢复出厂后解决

**Comment by qiwihui** [comment]
不明白你要问的问题，和你的描述不相关。
