### ISSUE TITLE
安装新版提示错误: syntax error: unexpected end of file (expecting "fi")

### ISSUE THREAD

**Issue by yoyobbs** [qiwihui/hiwifi-ss#6]
`
root@Hiwifi:/tmp# sh shadow.sh

/*教程请参考:极路由Shadowsocks家庭无痛翻墙实践*/
https://luolei.org/hiwifi-shadowsocks/
by @foru17

那一天,
人类终于回想起了,
曾经一度被他们所支配的恐怖,
还有被囚禁于鸟笼中的那份屈辱.

進撃の巨人 諫山創

'leep: invalid number '2
Building environment... 创建临时目录ing

Done! 成功创建临时目录!

'leep: invalid number '3
Downloading files... 下载插件ing

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  243k  100  243k    0     0   1570      0  0:02:38  0:02:38 --:--:-- 10980
Done! 下载完成

'leep: invalid number '3
Installing... 安装ing
shadow.sh: line 74: syntax error: unexpected end of file (expecting "fi")
`

**Comment by qiwihui** [comment]
@yoyobbs 这个问题应该是脚本在传输过程中改变了，请问你是直接在路由器上运行一键命令还是用其他的软件上传到路由器上的呢？

**Comment by hooverwang** [comment]
直接在路由器上运行的一键命令。硬件是极路由4，系统是9019

**Comment by yoyobbs** [comment]
是用winscp上传shadow.sh到tmp目录
然后进入tmp目录
sh shadow.sh

**Comment by yoyobbs** [comment]
您提示:新版本使用项目根目录下的 shadow.sh 脚本进行安装
所以我按上面的步骤操作有误？

**Comment by qiwihui** [comment]
@yoyobbs 你用以下的一键命令在极路由上安装这个插件：

```sh
cd /tmp && curl -k -o shadow.sh https://raw.githubusercontent.com/qiwihui/hiwifi-ss/master/shadow.sh && sh shadow.sh && rm shadow.sh
```

这个问题是因为windows和mac, linux在有些字符的编码上不一致，主要是`回车`的编码不一致，你从winscp上传的话会改变一些字符，导致脚本识别`sleep`命令出错。使用Unix风格保存这个脚本再上传到极路由的话没有问题，DOS风格（windows风格）会出问题。

**Comment by yoyobbs** [comment]
谢谢，我今晚更新后再留言回复，致谢

**Comment by yoyobbs** [comment]
按照您的一键方法，成功安装ss，感谢作者的无私风险，万分感谢

**Comment by qiwihui** [comment]
😄不谢~
