### ISSUE TITLE
极1S hc5661a 安装失败

### ISSUE THREAD

**Issue by DRJ31** [qiwihui/hiwifi-ss#61]
#### 问题描述
安装的时候显示“Error,请备份并重命名/etc/config/ss-redir 文件夹”

**Comment by Alexkun** [comment]
我头一次安装，成功了。你的情况可能是重复安装，需要去掉已有的配置文件。如果还不行的话，就把shadow.sh下下来看看相关源码

**Comment by qiwihui** [comment]
请参照 @Alexkun 方式操作。
