### ISSUE TITLE
极路由2ss没有高级设置

### ISSUE THREAD

**Issue by voodoozz** [qiwihui/hiwifi-ss#63]
#### 问题描述
系统版本 : HC5761A - 1.2.5.15805s   
两个问题
1. 不支持ipv6
2. 看不到高级设置按钮

**Comment by liangwenzhong** [comment]
极路由3也有这个问题
系统版本 : HC5861 - 1.2.5.15805s

**Comment by Torinomii** [comment]
安装1.2.5.15805s版本ss没有高级菜单.
HC5761A - 1.2.5.15805s

**Comment by BenjaminX** [comment]
HC5962 - 1.2.5.15805s
级路由4，ss没有高级菜单。

**Comment by billyjr** [comment]
HC5861 - 1.2.5.15805s
极路由3，ss也没有高级菜单

**Comment by Noodle-Soup** [comment]
Please refer to [https://github.com/qiwihui/hiwifi-ss/commit/d852806ddcebbc7196f66bc5e711fd4de11f9d26](url)

>  支持极路由新版 1.2.5.15805s
> 
> 1. 修正导入错误
> 2. 去除导入配置文件功能
> 3. **暂时隐藏高级设置功能**

**Comment by voodoozz** [comment]
关于ipv6 有办法支持吗？

**Comment by qiwihui** [comment]
高级设置功能的逻辑不是很清楚，影响整体功能，故先隐藏。

**Comment by mtndewxu** [comment]
高级设置现在是不是还没有开出来？我看了下高级里面好多功能都是我需要的哈哈。。。
