### ISSUE TITLE
uci: Entry not found

### ISSUE THREAD

**Issue by footballqq** [qiwihui/hiwifi-ss#64]
#### 问题描述
极路由版本
HC6361 - 1.2.5.16426s
安装成功 curl -k -o shadow.sh https://raw.githubusercontent.com/cllu/hiwifi-ss/hiwifi-v1.2.5/shadow.sh
可以进入路由器后台SS配置界面
但系统显示SS“未运行”
#### 运行结果
手动测试：
root@Hiwifi:~# /etc/init.d/gw-redsocks start
uci: Entry not found
gw_redsocks: applet not found

分析发现：这个没有结果（配置文件adv下面为空）
user_urls=$(uci get shadowsocks.adv.url)

**Comment by footballqq** [comment]
添加自定义hosts就没问题了
新问题是
iptables: Chain already exists

**Comment by qiwihui** [comment]
请尝试重新安装。
