### ISSUE TITLE
希望能增加OTA

### ISSUE THREAD

**Issue by FFlowerS** [qiwihui/hiwifi-ss#67]
服务器上做好了OTA，如果支持SSR的verify_sha1协议也可以呀

**Comment by hydrocode** [comment]
最新版的SS中已经移除OTA功能，因为它会带来更大隐患。https://github.com/shadowsocks/shadowsocks-libev/blob/master/debian/changelog

**Comment by qiwihui** [comment]
shadowsocks-libev 主分支在对于隐藏“客户端在访问什么网站”越走越远，对于保护“服务器在提供翻墙服务”上却不怎么下功夫，所以 OTA 是不会支持了，反正 3.0 版本也废弃了。
