### ISSUE TITLE
经常自动退出？

### ISSUE THREAD

**Issue by hybtw** [qiwihui/hiwifi-ss#68]
#### 问题描述
每天都会显示已运行未加速，是ss进程自动退出了？

**Comment by yuzhenyang** [comment]
我在极路由3，HC5861 - 1.2.5.15805s，有同样的的问题。
状态:	运行中 未加速
每天需要进极路由后台  Shadowsocks  重新保存一次才显示加速。

**Comment by q629988171** [comment]
一样的情况，GOOGLE经常打不开，进路由管理后台看，SS显示运行中 未加速 ，重新保存后正常

**Comment by qiwihui** [comment]
现阶段: 

  - 运行状态 指 ss-local 或者 gw_redsocks 程序是否运行
  - 加速指的是 能否连上 youtube

后端每7秒调一次接口进行判断，所以未加速可能是短暂未连上youtube。会在之后想办法稳定 ss 运行。

**Comment by q629988171** [comment]
[建议] 增加连续3次无法连接触发告警，减少误判；

**Comment by chntylz** [comment]
非常赞同，q629988171 
增加连续3次无法连接触发告警，减少误判；
如果3次之后 failed ，执行   /etc/init.d/gw-shadowsocks restart， 避免每次都要手动开关 Shadowsocks

**Comment by chntylz** [comment]
求教：
加速指的是 能否连上 youtube
后端每7秒调一次接口进行判断，所以未加速可能是短暂未连上youtube。会在之后想办法稳定 ss 运行。

shell脚本怎么实现的？ ping 命令吗？

**Comment by chntylz** [comment]
自己添加脚本，完美解决掉线（未运行 未加速）问题
https://github.com/chntylz/hiwifi-ss-1/blob/master/check_ss_status.sh
