### ISSUE TITLE
极路由4 HC5962 - 0.9019.1.13715s 安装失败

### ISSUE THREAD

**Issue by hooverwang** [qiwihui/hiwifi-ss#7]
无法安装成功。
环境是，一台hiwifi 2S 1.0.7；另一台为hiwifi 4 0.9019
均未成功。

其中，hiwifi 2s的提示如下：

root@Hiwifi:~# cd /tmp && curl -k -o shadow.sh https://raw.githubusercontent.com
/qiwihui/hiwifi-ss/master/shadow.sh && sh shadow.sh && rm shadow.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2578  100  2578    0     0    286      0  0:00:09  0:00:09 --:--:--   678

/_教程请参考:极路由Shadowsocks家庭无痛翻墙实践_/
https://luolei.org/hiwifi-shadowsocks/
by @foru17

那一天,
人类终于回想起了,
曾经一度被他们所支配的恐怖,
还有被囚禁于鸟笼中的那份屈辱.

進撃の巨人 諫山創

Building environment... 创建临时目录ing

Done! 成功创建临时目录!

Downloading files... 下载插件ing

curl: (6) Couldn't resolve host 'qiwihui.com'
Done! 下载完成

Installing... 安装ing
备份系统文件........[完成]
tar: can't open 'ss.tar.gz': No such file or directory
Done! 插件安装成功!

adding uninstall information... 准备删除临时文件...

cleanning temporary files... 清理临时文件ing

luci-cache does not exist! 无法找到luci-cache,请确定是否是极路由环境

the whole installation Success! 插件成功安装!
1987年9月14日21时07分
中国第一封电子邮件
从北京发往德国
越过长城，走向世界
Done! Hello World! 一切就绪,你好世界!
root@Hiwifi:/tmp#

**Comment by qiwihui** [comment]
@hooverwang  `luci-cache does not exist! 无法找到luci-cache,请确定是否是极路由环境` 这句话暂时可以忽略，所以你试着重启路由器看看有没有安装成功！还有界面上有显示出安装的`shadowsocks设置`吗？

**Comment by hooverwang** [comment]
重启之后，界面没有 Shadowsocks设置

**Comment by yoyobbs** [comment]
hooverwang 重启后，进入路由管理界面，点击“互联网”，就看到ss设置了。

**Comment by qiwihui** [comment]
@yoyobbs shadowsocks设置我放在"互联网"设置下作为二级菜单，你需要查看有没有这个设置。
未来应该会把这个设置移到一级菜单下吧，更方便些。

**Comment by hooverwang** [comment]
@qiwihui 现在一台极路由二已经安装上。另一台极路由4 HC5962 - 0.9019.1.13715s 安装之后，“互联网”这个一级菜单点开始一片空白了。估计9019和1.0.7文件结构还是不一样吧？我是小白～～

**Comment by qiwihui** [comment]
@hooverwang 0.9019.1.13715s 版本的极路由的界面我得去查查它的代码，我没有极路由4，估计这个问题得花一些时间。

你"互联网"界面的空白的问题可以找到之前文件的备份，将`/usr/lib/lua/luci/view/admin_web/network/index.htm.ssbak`文件重命名为`/usr/lib/lua/luci/view/admin_web/network/index.htm`, 就可以修复了。

**Comment by qiwihui** [comment]
@hooverwang 请问你现在界面恢复了吗?

**Comment by techfanseric** [comment]
@hooverwang 我遇到与你一样的问题,已经修复了. 具体方法如下:
下载我上传的index.htm.zip解压得到index.htm放到桌面,通过scp指令复制到路由器/usr/lib/lua/luci/view/admin_web/network/路径下,参考指令如下(我的是OSX系统)
scp -P1022 /Users/Eric/Desktop/index.htm root@192.168.199.1:/usr/lib/lua/luci/view/admin_web/network/
然后重启路由器进入互联网界面就看到shadowsocks并且可以正常使用啦
[index.htm.zip](https://github.com/qiwihui/hiwifi-ss/files/416388/index.htm.zip)

**Comment by techfanseric** [comment]
@qiwihui 我上传的附件中index.htm是最新极路由4在系统版本 : HC5962 - 0.9019.1.13715s 下的互联网配置界面htm文件(已经根据你的shadowsocks设置需求添加了相应的结构),本次提的问题是因为以前老版的互联网设置htm文件结构与新固件的htm文件结构不一样导致互联网配置界面出现空白且重启后宕机的情况.所以需要麻烦你修复这个问题给更多人带来更便利的安装体验,在此拜托大神啦.
[Archive.zip](https://github.com/qiwihui/hiwifi-ss/files/416390/Archive.zip)

**Comment by qiwihui** [comment]
@techfanseric 我会尽快查看一下这个问题，并给出解决方案的

**Comment by qiwihui** [comment]
@techfanseric 你在附件`Archive.zip`中的`index.htm`文件和`index.html.0813bak`时一样的，是我新修改的界面，请问是不是传错了？

**Comment by runningrou** [comment]
@qiwihui 自己修改部分代码后点击互联网空白的问题倒是解决了，但是配置好ss信息后点击保存，一直会停留在loading状态，json上传也显示失败，极路由4

**Comment by qiwihui** [comment]
@runningrou 现在这个脚本对极路由4的支持还没有完全弄完，所以停留在loading状态我还没研究清楚。
另，json上传好像一直不能用，所以我打算暂时移除这个功能。

**Comment by runningrou** [comment]
@qiwihui HC5962(极路由4)可以正常使用，方法如下：进入hiwifi管理后台>智能插件>路由器信息>加入预发布版本(选择预发布版，此时会推送更新固件1.1.4.14678s)，更新固件后，按流程安装ss插件，填写ss信息，重启路由后，科学上网成功。

**Comment by qiwihui** [comment]
@runningrou 👍，非常感谢你提供的方法，我想应该是极路由4更新到新版本之后和其他版极路由的页面结构一致了，所以这个问题暂时可以通过更新路由器版本解决。

**Comment by qiwihui** [comment]
@hooverwang 你可以按照 @runningrou 提供的方法进行更新

**Comment by hooverwang** [comment]
@qiwihui @runningrou HC5962 - 1.1.4.14678s升级后安装插件没有设置ss的按钮啊？

**Comment by qiwihui** [comment]
referring to #38

**Comment by 1sn0m4d** [comment]
你好，请教一个，HIWIFI 4安装了 ss 以后如果在在 hiwifi路由下面拨入PPTP的VPN 是否走的ss通道呢。有这样试验过吗？

**Comment by qiwihui** [comment]
升级新版极路由并安装新版插件
