### ISSUE TITLE
极路由4+SS后微博视频无法播放

### ISSUE THREAD

**Issue by ikkyu0319** [qiwihui/hiwifi-ss#70]
#### 问题描述
极路由4 配置Shadowsocks ，开启智能模式，加速DNS选择谷歌

现在手机，PC 刷微博视频经常加载不出来，秒拍看视频也非常慢，有时也加载不出来，

爱奇艺，Youtube的视频都正常，微信文章里的视频有时也加载不出来；

#### 运行结果

关闭ss后，所有视频都能播放（Youtube当然不行啊）

有木有网友也遇到类似问题，有什么更好的解决办法么？

**Comment by qiwihui** [comment]
只能模式其实是白名单模式，所以如果访问的地址不在白名单里，会选择翻墙。
解决办法：
1. 添加服务器 ip 到白名单中；
2. 之后增加黑白名单选择；

**Comment by ikkyu0319** [comment]
@qiwihui 计划什么时候支持白名单选择呢~~

非常期待~
