### ISSUE TITLE
shadowsocks是不是不会开机自启动

### ISSUE THREAD

**Issue by mountainguan** [qiwihui/hiwifi-ss#73]
#### 问题描述
我给我的极路由1s装了，然后运行时间一长就会down掉，要重新关掉ss再启动ss服务
然后有一段时间我给极路由安装上自动重启的插件，每天重启一次来希望保证服务正常运行。
可是更新了几个极路由版本以后，这招也没用了，ss还是挂了，而且还因为ss挂了影响到了本来可以访问的网站，像百度这一类，会变得响应非常慢。弄得我现在每次用完就随手关掉

**Comment by fujiwara-takumi** [comment]
极路由4增强版遇到一样的问题，不知道什么情况。

**Comment by qiwihui** [comment]
试着重新安装一下新版本插件吧
