### ISSUE TITLE
安装设置好之后提示状态：“运行中，未加速”

### ISSUE THREAD

**Issue by wly1996** [qiwihui/hiwifi-ss#74]
#### 问题描述
开启的全局代理，保证ss服务一切正常，但是在路由器开启之后显示“运行中，未加速”，而且所有设备都无法连接出去，请问如何解决？使用的是ipv6地址，但是ipv4可以使用

**Comment by qiwihui** [comment]
已经修复了这个问题，试着重新安装一下插件吧

**Comment by chntylz** [comment]
运行一段时间之后，偶尔 由 “运行中，已加速” -> “运行中，未加速”，什么原因导致的呢

 function update_status() {
     var request_date = {};
     $.getJSON("<%=luci.dispatcher.build_url("api", "geewan","get_shadowsocks_status")%>",request_date,function(rsp)
     {
         var status = "";
         if (rsp.code == 0){
             if(rsp.status == "stopped"){
                 status = "<span style='color:red'>未运行</span>";
             } else if (rsp.status == "running") {
                 if (rsp.accel == "yes")
                     status = "运行中 <span style='color:green'>已加速</span>";
                 else
                     status = "运行中 <span style='color:red'>未加速</span>";
             } else {
                 status = "未知";
             }
             $("#con_stauts").html(status);
         }
     })

(rsp.accel == "yes")  改变量是执行什么shell 命令的结果呢，求赐教
