### ISSUE TITLE
极路由贰安装了之后，互联网选项卡不能打开

### ISSUE THREAD

**Issue by caojm93** [qiwihui/hiwifi-ss#76]
#### 问题描述
新版系统按照教程安装之后打不开互联网那个选项卡
[http://ok8a4ojz7.bkt.clouddn.com/17-3-22/16162821-file_1490151924348_1cb1.png](url)
#### 运行结果
运行结果正常，只是打不开界面

**Comment by caojm93** [comment]
图片地址需要复制出来粘贴到地址栏查看

**Comment by caojm93** [comment]
版本是 
HC5761 - 1.2.5.15805s

**Comment by qiwihui** [comment]
试试重启路由器

**Comment by caojm93** [comment]
重启过了，也还是不行😂

**Comment by qiwihui** [comment]
@caojm93 试着重新安装一下插件吧

**Comment by qiwihui** [comment]
已经更新了一般，试着重新安装一下插件吧
