### ISSUE TITLE
有些网站打不开如何更新规则

### ISSUE THREAD

**Issue by wzs1990** [qiwihui/hiwifi-ss#77]
#### 问题描述
有些网站打不开如何更新规则GFWList能否实现无法打开的网站手动添加地址
#### 运行结果
有些网站打不开如何更新规则

**Comment by wtser** [comment]
不是有管理界面可以手动添加网址的么

**Comment by wzs1990** [comment]
www.pinterest.com 这个网址不能正常打开是不是GFWList有问题

**Comment by jndxhuxiehang** [comment]
可以参考我写的项目可以更新

**Comment by jndxhuxiehang** [comment]
@wtser 这个网站是新加入的，原项目的list是没有该网站的，建议前往我的项目[jndxhuxiehang/-dnslist-](https://github.com/jndxhuxiehang/-dnslist-)去更新，应该可以解决
