### ISSUE TITLE
能否研究下这个版本的插件

### ISSUE THREAD

**Issue by chuan0932** [qiwihui/hiwifi-ss#8]
![qq 20160810200842](https://cloud.githubusercontent.com/assets/20948423/17553202/1c33780a-5f37-11e6-954a-f66e7bd550f8.png)

**Comment by qiwihui** [comment]
请问具体是要我怎么研究这个插件呢？
这个插件是stray.love编写的，他在他的博客上讲了很多关于这个插件的内容，你可以向他询问这个这个插件的安装方法。同样，这个插件也是由三流火最早的插件修改而来，作者在上边做的工作比我的多了很多，我使用的版本比这个版本老，所以暂时还没有太多的功能。在我修改下这个插件过程中，stray.也给我了很多帮助。

**Comment by zwdotnet** [comment]
能否告知一下stray的博客地址呢

**Comment by qiwihui** [comment]
@zwdotnet https://stray.love/

**Comment by zwdotnet** [comment]
@qiwihui  thk

**Comment by qiwihui** [comment]
close.
