### ISSUE TITLE
版本HC5861-1.2.5.15805s,显示运行中，但是无法连上墙外网站

### ISSUE THREAD

**Issue by Rock610** [qiwihui/hiwifi-ss#80]
#### 问题描述
版本HC5861-1.2.5.15805s 安装成功，并且配置成功后显示运行中。但是无论MAC或者Windows都无法上去外网。但是手机连接wifi就可以上。很奇怪。PC使用shawdowsocksX客户端可以上。

**Comment by caojm93** [comment]
同情况，好奇怪

**Comment by Rock610** [comment]
解决了。是DNS和IP设置问题，改为自动就行了，不知道别人是什么情况
