### ISSUE TITLE
路由器上的ss很慢，不超过20Mbps

### ISSUE THREAD

**Issue by Loukky** [qiwihui/hiwifi-ss#81]
#### 问题描述
在路由器上面挂ss的话，速度似乎被限速了一样，不会超过20Mbps，但是如果在手机或者电脑上面挂ss，同时将路由器的ss关闭，这时候速度就会正常，达到70-80Mbps

**Comment by reaCodes** [comment]
@Loukky 因为SS的处理器的数据处理能力达不到手机电脑的水平

**Comment by Skyepose** [comment]
其实我想知道这个速度上是不是有一定的差距？如果是极路由4 加强班会不会比极路由3 Pro好很多？
