### ISSUE TITLE
极一S HC5661A 重启路由器后，SS无法使用，上网信息丢失

### ISSUE THREAD

**Issue by HUSH-Wang** [qiwihui/hiwifi-ss#85]
### 问题描述
极一S HC5661A - 1.2.5.15805s  ，安装完成后使用正常。
断电，重启路由器后，WIFI SSID、密码等信息、上网信息恢复出厂默认设置，需要手动重新设置才能使用。
路由器插件需要手动开启才能正常使用。
SS设置提示“操作失败，请求的接口不存在”。
重新安装SS可正常使用，但重启后仍出现上述现象。

**Comment by gstone7** [comment]
@HUSH-Wang 互联网栏下一直处在加载状态，你有碰到这个问题吗？

**Comment by qiwihui** [comment]
请安装戏版本试试。
入口在最左侧菜单上。
