### ISSUE TITLE
极路由Go能刷成功，就是点击“shadowsocks加速”不出来界面

### ISSUE THREAD

**Issue by aimuch** [qiwihui/hiwifi-ss#87]
#### 问题描述
用旧的方式和方式都试过了，都能刷成功，就是单击进去不显示：
首先进入后台，由于极路由go电脑端没有web访问方式所以将mobile以及以后的改成web就可以访问web方式了。

**Comment by qiwihui** [comment]
已经修复了入口，在左侧菜单，你重新安装试试。
暂时没有做 mobile的界面。
