### ISSUE TITLE
luci-cache does not exist! 无法找到luci-cache,请确定是否是极路由环境

### ISSUE THREAD

**Issue by fujiwara-takumi** [qiwihui/hiwifi-ss#88]
#### 问题描述
我的是15808的系统
`cd /tmp && curl -k -o shadow.sh https://raw.githubusercontent.com/qiwihui/hiwifi-ss/master/shadow.sh && sh shadow.sh 12515805s && rm shadow.sh`
运行这一段程序下载速度太慢，就替换成了博客里面那个地址.
`http://cdn.is26.com/file/hiwifi/shadow.sh`
运行提示安装完成但是其中有一行如下
`luci-cache does not exist! 无法找到luci-cache,请确定是否是极路由环境`
#### 运行结果
还未重启，互联网菜单下没发现shadowsocks设置项

**Comment by jndxhuxiehang** [comment]
可以rm掉再多装几种试试，都试一下

**Comment by qiwihui** [comment]
`luci-cache does not exist! 无法找到luci-cache,请确定是否是极路由环境` 不影响使用。
重新安装即可
