### ISSUE TITLE
极路由的官方rom已经更新到1.3.4.18145s

### ISSUE THREAD

**Issue by wybb** [qiwihui/hiwifi-ss#89]
现在的ss版本支持不？

**Comment by yuxden2** [comment]
确认支持

**Comment by Myoko** [comment]
官方现在依然是125 哪里来的134？

**Comment by fujiwara-takumi** [comment]
@yuxden2 1.3.4.18145s 你那边是第几代路由器，确认支持用的是两个代码中的哪一个？
`cd /tmp && curl -k -o shadow.sh https://raw.githubusercontent.com/qiwihui/hiwifi-ss/master/shadow.sh && sh shadow.sh 12515805s && rm shadow.sh
`
用的这个15805s的代码吗？

**Comment by namti** [comment]
极路由 GO
系统版本 : HC5611 - 1.3.4.18145s

**Comment by qiwihui** [comment]
已支持 1.3.4.18145s
```sh
cd /tmp && curl -k -o shadow.sh https://raw.githubusercontent.com/qiwihui/hiwifi-ss/master/shadow.sh && sh shadow.sh && rm shadow.sh
```

**Comment by namti** [comment]
覆盖安装的，还是一样，确定是这条命令吗？
cd /tmp && curl -k -o shadow.sh https://raw.githubusercontent.com/qiwihui/hiwifi-ss/master/shadow.sh && sh shadow.sh && rm shadow.sh
