### ISSUE TITLE
关于更新大陆白名单里面大陆的IP段问题

### ISSUE THREAD

**Issue by Loukky** [qiwihui/hiwifi-ss#90]
#### 运行结果

这个插件非常好用，大陆白名单我也很喜欢，但是目前有一个问题如果能够解决就是锦上添花了，启用SS的时候，我玩魔兽的情况下，也会走代理，这就导致了我的PING有100多，非常的不方便，请教如何更新其中的大陆白名单的IP段？

**Comment by q629988171** [comment]
添加服务器 ip 到白名单中，参见 #39
