### ISSUE TITLE
1.3.4.18145s 提供了 极路由本地插件

### ISSUE THREAD

**Issue by BenjaminX** [qiwihui/hiwifi-ss#91]
新版 ROM 提供本地插件加载能力

**Comment by q629988171** [comment]
@BenjaminX 本地插件加载能力 ，插件不需要上传到云端，也不需要ROOT，就可以安装？

**Comment by Myoko** [comment]
极路由官方最新的固件依然是1.2.5 哪里来的1.3.4.18145s？

**Comment by gstone7** [comment]
@BenjaminX 你是极路由几？我的极路由1s还没有收到这个版本的升级提示。

**Comment by BenjaminX** [comment]
极路由4增强版

**Comment by fujiwara-takumi** [comment]
@BenjaminX 1.3.4 18145s 能用这个SS插件么

**Comment by qiwihui** [comment]
@fujiwara-takumi 可以

**Comment by MrWanyan** [comment]
方便说一下SS最新固件SS插件的安装地址么？

**Comment by silentred** [comment]
系统自动升级到了， 系统版本 : HC5861B - 1.3.5.18462s ，看不到 ss插件了，再次安装也不显示图标了，我擦

**Comment by qiwihui** [comment]
@silentred 试试重新安装并查看左侧菜单即可找到新入口

**Comment by cbigdream** [comment]
本地安装显示安装包损坏

**Comment by nkcfc** [comment]
极1s 1.4.10.20837s 没看到本地插件的选项，求指点。 极X倒是看到了。

**Comment by q629988171** [comment]
> 本地安装显示安装包损坏

本地插件目前没人开发，官方只出了两个，一个SS，一个去广告，有在极先锋群发布
