### ISSUE TITLE
极路由1S读不出1G的内存卡，有root，大佬求解

### ISSUE THREAD

**Issue by 1265578519** [qiwihui/hiwifi-ss#94]
#### 问题描述
极路由1S读不出1G的内存卡，有root，大佬求解
#### 运行结果
http://i2.muimg.com/572924/f4bb076fb350645d.png

**Comment by jndxhuxiehang** [comment]
都提示你没法识别了，去买个大点的内存卡吧

**Comment by qiwihui** [comment]
按给的提示操作。
