### ISSUE TITLE
HC5861 - 1.3.4.18145s 装完后，互联网进去一直菊花

### ISSUE THREAD

**Issue by raoxinyi** [qiwihui/hiwifi-ss#97]
#### 问题描述
HC5861 - 1.3.4.18145s 装完重启，互联网菜单进去一直菊花

装的是这个：
cd /tmp && curl -k -o shadow.sh https://raw.githubusercontent.com/qiwihui/hiwifi-ss/master/shadow.sh && sh shadow.sh && rm shadow.sh

#### 运行结果
互联网菜单进去一直菊花

**Comment by qiwihui** [comment]
还未支持 `1.3.4.18145s`， 请使用一下命令恢复
```
mv /usr/lib/lua/luci/view/admin_web/network/index.htm.ssbak /usr/lib/lua/luci/view/admin_web/network/index.htm
```

**Comment by raoxinyi** [comment]
感谢，已恢复，期待插件升级！

**Comment by qiwihui** [comment]
已支持 `1.3.4.18145s`，可以安装了

```sh
cd /tmp && curl -k -o shadow.sh https://raw.githubusercontent.com/qiwihui/hiwifi-ss/master/shadow.sh && sh shadow.sh && rm shadow.sh
```

**Comment by raoxinyi** [comment]
昨晚安装了，显示正常了

但发现配置ss并重启后，上不了网，把ss开关给关了，能正常上网了。
暂时只能先关掉了。但每次重启后都会自动连上ss，导致上不了网。

感觉程序的逻辑有点问题，将开关设置为关之后，重启后默认也应该是关闭状态才对吧。

**Comment by xu62011** [comment]
我是HC5761 - 1.3.4.18145s
也是安装的hiwifi 1.2.5.15805s后互联网状态菊花了，但是能用
看你说安装1.3.4.18145s这个版本的后无网，幸好= = ！

**Comment by 823michael** [comment]
报告一下，极路由4，HC5962 - 1.3.4.18145s，刷了最新的固件之后，有@raoxinyi一样的问题，打开SS之后，整个路由器都无法上网了。要关闭才可以正常上网，但是就无法使用SS了。。
望修复，感谢！

**Comment by qiwihui** [comment]
已经修复了，重新下载安装即可
